#!/usr/bin/env bash
set -euo pipefail

# Strict Any2Any-style Sonic-source LoRA smoke on the X2 receiver-safe motion cache.
# Scope follows Any2Any's lightweight adaptation idea:
#   train actor dynamics decoder LoRA + critic LoRA + action std
#   freeze FSQ, encoders, kinematic decoder, and source base weights
#
# This script intentionally uses the tiny receiver_safe_clean subset:
#   stand + wave + balance_shift
# It is only a plumbing/safety smoke, not a useful policy training run.

ROOT="/home/humanplus/x2_teleop_final"
PROJECT_ROOT="/home/humanplus/projects/ZHY/CWI_CrossEmbodiment_Sim"
SANDBOX="${ROOT}/x2_sonic/sonic_x2_sandbox/gear_sonic"
LOG_ROOT="${PROJECT_ROOT}/logs"
CHECKPOINT="${CHECKPOINT:-/home/humanplus/humanoid-GPT/A/sonic_release/last.pt}"
MOTION_FILE="${MOTION_FILE:-/home/humanplus/x2_teleop_final/x2_sonic/motion_lib_x2/receiver_safe_clean_split}"
EXP_CONFIG="${EXP_CONFIG:-manager/universal_token/all_modes/sonic_x2_receiver_safe_clean}"

RUN_NAME="${RUN_NAME:-x2_sonic_any2any_lora_receiver_safe_smoke}"
RUN_KIND="${RUN_KIND:-smoke}"
NUM_CRITICS="${NUM_CRITICS:-1}"
MULTI_CRITIC_ADVANTAGE_WEIGHTS="${MULTI_CRITIC_ADVANTAGE_WEIGHTS:-null}"
DCPEFT_REWARD_CONTRACT="${DCPEFT_REWARD_CONTRACT:-}"
DCPEFT_REWARD_AUDIT_JSONL="${DCPEFT_REWARD_AUDIT_JSONL:-${PROJECT_ROOT}/results/${RUN_NAME}_reward_contract.jsonl}"
RESUME="${RESUME:-false}"
RESUME_KEEP_EXPERIMENT_DIR="${RESUME_KEEP_EXPERIMENT_DIR:-false}"
SEED="${SEED:-0}"
NUM_ENVS="${NUM_ENVS:-1}"
STEPS_PER_ENV="${STEPS_PER_ENV:-2}"
ITERS="${ITERS:-1}"
MOTIONS="${MOTIONS:-1}"
ADAPTIVE_SAMPLING_ENABLED="${ADAPTIVE_SAMPLING_ENABLED:-true}"
ADAPTIVE_SAMPLING_BIN_SIZE="${ADAPTIVE_SAMPLING_BIN_SIZE:-50}"
ADAPTIVE_SAMPLING_UNIFORM_RATE="${ADAPTIVE_SAMPLING_UNIFORM_RATE:-0.1}"
ADAPTIVE_SAMPLING_PRE_FAILURE_WINDOW="${ADAPTIVE_SAMPLING_PRE_FAILURE_WINDOW:-200}"
ADAPTIVE_SAMPLING_MAX_PROB_PER_BIN="${ADAPTIVE_SAMPLING_MAX_PROB_PER_BIN:-null}"
ADAPTIVE_SAMPLING_MAX_PROB_PER_MOTION="${ADAPTIVE_SAMPLING_MAX_PROB_PER_MOTION:-null}"
USE_PAIRED_MOTIONS="${USE_PAIRED_MOTIONS:-false}"
START_FROM_FIRST_FRAME="${START_FROM_FIRST_FRAME:-false}"
PRESERVE_AUTO_RESET_FRAME_ZERO="${PRESERVE_AUTO_RESET_FRAME_ZERO:-false}"
CONTACT_PHASE_SYNC_ENABLED="${CONTACT_PHASE_SYNC_ENABLED:-false}"
CONTACT_PHASE_SYNC_LOWER_BODY_ONLY="${CONTACT_PHASE_SYNC_LOWER_BODY_ONLY:-false}"
CONTACT_PHASE_SYNC_LOWER_BODY_BLEND="${CONTACT_PHASE_SYNC_LOWER_BODY_BLEND:-1.0}"
CONTACT_PHASE_SYNC_LOWER_BODY_PAIR_BLENDS="${CONTACT_PHASE_SYNC_LOWER_BODY_PAIR_BLENDS:-[]}"
CONTACT_PHASE_SYNC_LEAD_STEPS="${CONTACT_PHASE_SYNC_LEAD_STEPS:-10}"
CONTACT_PHASE_SYNC_LAG_STEPS="${CONTACT_PHASE_SYNC_LAG_STEPS:-10}"
CONTACT_PHASE_SYNC_MAX_ADVANCE_PER_STEP="${CONTACT_PHASE_SYNC_MAX_ADVANCE_PER_STEP:-2}"
CONTACT_PHASE_SYNC_FORCE_THRESHOLD="${CONTACT_PHASE_SYNC_FORCE_THRESHOLD:-20.0}"
CONTACT_LOAD_GATE_ENABLED="${CONTACT_LOAD_GATE_ENABLED:-false}"
CONTACT_LOAD_GATE_PREVIEW_STEPS="${CONTACT_LOAD_GATE_PREVIEW_STEPS:-10}"
CONTACT_LOAD_GATE_MAX_HOLD_STEPS="${CONTACT_LOAD_GATE_MAX_HOLD_STEPS:-10}"
CONTACT_LOAD_GATE_MIN_STANCE_SHARE="${CONTACT_LOAD_GATE_MIN_STANCE_SHARE:-0.70}"
CONTACT_LOAD_GATE_MIN_TOTAL_LOAD_N="${CONTACT_LOAD_GATE_MIN_TOTAL_LOAD_N:-100.0}"
LOWER_BODY_REFERENCE_DELAY_STEPS="${LOWER_BODY_REFERENCE_DELAY_STEPS:-0}"
PAIRED_START_MODE_PATTERN="${PAIRED_START_MODE_PATTERN:-[]}"
FREEZE_FRAME_AUG="${FREEZE_FRAME_AUG:-true}"
TERRAIN_TYPE="${TERRAIN_TYPE:-plane}"
ACTION_SCALE_MULT="${ACTION_SCALE_MULT:-1.0}"
ACTION_SCALE_JOINT_MULTIPLIERS="${ACTION_SCALE_JOINT_MULTIPLIERS:-}"
if [[ -z "${ACTION_SCALE_JOINT_MULTIPLIERS}" ]]; then
  ACTION_SCALE_JOINT_MULTIPLIERS="{}"
fi
ACTUATOR_RESPONSE_MODE="${ACTUATOR_RESPONSE_MODE:-off}"
ACTUATOR_RESPONSE_PROFILE="session03_group"
ACTUATOR_RESPONSE_INCLUDE_IDEAL=false
ACTUATOR_RESPONSE_STRENGTH="${ACTUATOR_RESPONSE_STRENGTH:-1.0}"
ACTUATOR_RESPONSE_DELAY_STRENGTH="${ACTUATOR_RESPONSE_DELAY_STRENGTH:-}"
ACTUATOR_RESPONSE_FILTER_STRENGTH="${ACTUATOR_RESPONSE_FILTER_STRENGTH:-}"
ACTUATOR_RESPONSE_IDEAL_FRACTION="${ACTUATOR_RESPONSE_IDEAL_FRACTION:-}"
ACTUATOR_RESPONSE_CONTEXT_OVERRIDE="${ACTUATOR_RESPONSE_CONTEXT_OVERRIDE:-null}"
ACTION_PREEMPHASIS_ENABLED="${ACTION_PREEMPHASIS_ENABLED:-false}"
ACTION_PREEMPHASIS_STRENGTH="${ACTION_PREEMPHASIS_STRENGTH:-0.0}"
ACTION_PREEMPHASIS_MAX_DELTA_RAD="${ACTION_PREEMPHASIS_MAX_DELTA_RAD:-0.05}"
ACTION_PREEMPHASIS_GROUPS="${ACTION_PREEMPHASIS_GROUPS:-[legs,feet,waist]}"
ACTUATOR_GAIN_RANDOMIZATION="${ACTUATOR_GAIN_RANDOMIZATION:-off}"
RIGID_BODY_MASS_RANGE="${RIGID_BODY_MASS_RANGE:-[0.8,2.5]}"
VR_WRIST_OFFSET_MODE="${VR_WRIST_OFFSET_MODE:-current}"
EE_WRIST_LINK="${EE_WRIST_LINK:-yaw}"
REWARD_WRIST_LINK="${REWARD_WRIST_LINK:-roll}"
REWARD_POINT_MODE="${REWARD_POINT_MODE:-x2_5point}"
TRACKED_BODY_SET="${TRACKED_BODY_SET:-x2_full33}"
ANTI_SHAKE_BODY_NAMES="${ANTI_SHAKE_BODY_NAMES:-[left_wrist_yaw_link,right_wrist_yaw_link,head_link]}"
WRIST_DIAGNOSTICS="${WRIST_DIAGNOSTICS:-false}"
RENDER_RESULTS="${RENDER_RESULTS:-false}"
RENDER_RECORDERS="${RENDER_RECORDERS:-empty}"
RENDER_WIDTH="${RENDER_WIDTH:-640}"
RENDER_HEIGHT="${RENDER_HEIGHT:-480}"
RENDER_FRAME_SKIP="${RENDER_FRAME_SKIP:-2}"
MAX_RENDER_ENVS="${MAX_RENDER_ENVS:-1}"
ANCHOR_POS_THRESHOLD="${ANCHOR_POS_THRESHOLD:-0.15}"
ANCHOR_POS_XY_TERMINATION_ENABLED="${ANCHOR_POS_XY_TERMINATION_ENABLED:-false}"
ANCHOR_POS_XY_THRESHOLD="${ANCHOR_POS_XY_THRESHOLD:-0.20}"
ANCHOR_ORI_FULL_THRESHOLD="${ANCHOR_ORI_FULL_THRESHOLD:-0.2}"
EE_BODY_POS_THRESHOLD="${EE_BODY_POS_THRESHOLD:-0.15}"
FOOT_POS_XYZ_THRESHOLD="${FOOT_POS_XYZ_THRESHOLD:-0.2}"
VR_TRACKING_REWARD_WEIGHT="${VR_TRACKING_REWARD_WEIGHT:-2.0}"
EE_HEIGHT_REWARD_WEIGHT="${EE_HEIGHT_REWARD_WEIGHT:-0.0}"
EE_HEIGHT_REWARD_STD="${EE_HEIGHT_REWARD_STD:-0.1}"
ANCHOR_POS_REWARD_WEIGHT="${ANCHOR_POS_REWARD_WEIGHT:-0.5}"
ANCHOR_POS_REWARD_STD="${ANCHOR_POS_REWARD_STD:-0.3}"
ANCHOR_LINVEL_REWARD_WEIGHT="${ANCHOR_LINVEL_REWARD_WEIGHT:-0.0}"
ANCHOR_LINVEL_REWARD_STD="${ANCHOR_LINVEL_REWARD_STD:-0.1}"
ANCHOR_PATH_ERROR_WEIGHT="${ANCHOR_PATH_ERROR_WEIGHT:-0.0}"
ANCHOR_PATH_ALONG_TOLERANCE_M="${ANCHOR_PATH_ALONG_TOLERANCE_M:-0.03}"
ANCHOR_PATH_CROSS_TOLERANCE_M="${ANCHOR_PATH_CROSS_TOLERANCE_M:-0.06}"
ANCHOR_PATH_ALONG_NORMALIZATION_M="${ANCHOR_PATH_ALONG_NORMALIZATION_M:-0.10}"
ANCHOR_PATH_CROSS_NORMALIZATION_M="${ANCHOR_PATH_CROSS_NORMALIZATION_M:-0.12}"
ANCHOR_PATH_MIN_LENGTH_M="${ANCHOR_PATH_MIN_LENGTH_M:-0.02}"
ANCHOR_ORI_REWARD_WEIGHT="${ANCHOR_ORI_REWARD_WEIGHT:-0.5}"
RELATIVE_BODY_POS_REWARD_WEIGHT="${RELATIVE_BODY_POS_REWARD_WEIGHT:-1.0}"
SINGLE_SUPPORT_TRACKING_PREPARATION_FUTURE_FRAME_INDEX="${SINGLE_SUPPORT_TRACKING_PREPARATION_FUTURE_FRAME_INDEX:-0}"
SINGLE_SUPPORT_ANCHOR_LATERAL_SCALE="${SINGLE_SUPPORT_ANCHOR_LATERAL_SCALE:-1.0}"
SINGLE_SUPPORT_STANCE_BODY_SCALE="${SINGLE_SUPPORT_STANCE_BODY_SCALE:-1.0}"
SINGLE_SUPPORT_STANCE_FOOT_SCALE="${SINGLE_SUPPORT_STANCE_FOOT_SCALE:-1.0}"
JOINT_LIMIT_REWARD_WEIGHT="${JOINT_LIMIT_REWARD_WEIGHT:--10.0}"
SELECTED_JOINT_TRACKING_REWARD_WEIGHT="${SELECTED_JOINT_TRACKING_REWARD_WEIGHT:-0.0}"
SELECTED_JOINT_TRACKING_REWARD_STD="${SELECTED_JOINT_TRACKING_REWARD_STD:-0.15}"
SELECTED_JOINT_TRACKING_NAMES="${SELECTED_JOINT_TRACKING_NAMES:-[waist_pitch_joint,waist_roll_joint]}"
FEET_ACC_REWARD_WEIGHT="${FEET_ACC_REWARD_WEIGHT:--2.5e-6}"
FOOT_CONTACT_PHASE_REWARD_WEIGHT="${FOOT_CONTACT_PHASE_REWARD_WEIGHT:-0.0}"
FOOT_CONTACT_FORCE_THRESHOLD="${FOOT_CONTACT_FORCE_THRESHOLD:-20.0}"
FOOT_CONTACT_SWING_CONTACT_COST="${FOOT_CONTACT_SWING_CONTACT_COST:-1.0}"
FOOT_CONTACT_MISSED_STANCE_COST="${FOOT_CONTACT_MISSED_STANCE_COST:-0.5}"
FOOT_CONTACT_CONTINUOUS_LOAD="${FOOT_CONTACT_CONTINUOUS_LOAD:-false}"
FOOT_CONTACT_CONTINUOUS_LOAD_MODE="${FOOT_CONTACT_CONTINUOUS_LOAD_MODE:-absolute}"
FOOT_CONTACT_SWING_FORCE_NORMALIZER="${FOOT_CONTACT_SWING_FORCE_NORMALIZER:-250.0}"
FOOT_CONTACT_SUPPORT_FORCE_FRACTION_OF_WEIGHT="${FOOT_CONTACT_SUPPORT_FORCE_FRACTION_OF_WEIGHT:-0.60}"
FOOT_CONTACT_LEFT_SWING_COST_SCALE="${FOOT_CONTACT_LEFT_SWING_COST_SCALE:-1.0}"
FOOT_CONTACT_RIGHT_SWING_COST_SCALE="${FOOT_CONTACT_RIGHT_SWING_COST_SCALE:-1.0}"
FOOT_CONTACT_PREPARATION_FUTURE_FRAME_INDEX="${FOOT_CONTACT_PREPARATION_FUTURE_FRAME_INDEX:-0}"
FOOT_CONTACT_PREPARATION_PRESERVE_DOUBLE_CONTACT="${FOOT_CONTACT_PREPARATION_PRESERVE_DOUBLE_CONTACT:-false}"
SWING_FOOT_HEIGHT_REWARD_WEIGHT="${SWING_FOOT_HEIGHT_REWARD_WEIGHT:-0.0}"
SWING_FOOT_HEIGHT_REWARD_STD="${SWING_FOOT_HEIGHT_REWARD_STD:-0.025}"
SINGLE_SUPPORT_COM_REWARD_WEIGHT="${SINGLE_SUPPORT_COM_REWARD_WEIGHT:-0.0}"
SINGLE_SUPPORT_COM_NORMALIZATION_M="${SINGLE_SUPPORT_COM_NORMALIZATION_M:-0.10}"
SINGLE_SUPPORT_COM_PREPARATION_FUTURE_FRAME_INDEX="${SINGLE_SUPPORT_COM_PREPARATION_FUTURE_FRAME_INDEX:-0}"
REFERENCE_STANCE_FOOT_SLIP_REWARD_WEIGHT="${REFERENCE_STANCE_FOOT_SLIP_REWARD_WEIGHT:-0.0}"
REFERENCE_STANCE_FOOT_SLIP_NORMALIZATION_MPS="${REFERENCE_STANCE_FOOT_SLIP_NORMALIZATION_MPS:-0.50}"
INTERFOOT_RELATIVE_POS_REWARD_WEIGHT="${INTERFOOT_RELATIVE_POS_REWARD_WEIGHT:-0.0}"
INTERFOOT_RELATIVE_POS_REWARD_STD="${INTERFOOT_RELATIVE_POS_REWARD_STD:-0.15}"
FOOT_CONTACT_LABEL_MODE="${FOOT_CONTACT_LABEL_MODE:-legacy_absolute}"
FOOT_CONTACT_GROUND_PERCENTILE="${FOOT_CONTACT_GROUND_PERCENTILE:-0.05}"
FOOT_CONTACT_HEIGHT_MARGIN_M="${FOOT_CONTACT_HEIGHT_MARGIN_M:-0.025}"
FOOT_CONTACT_VERTICAL_SPEED_MAX_MPS="${FOOT_CONTACT_VERTICAL_SPEED_MAX_MPS:-0.25}"
FOOT_CONTACT_MAX_GROUND_BAND_M="${FOOT_CONTACT_MAX_GROUND_BAND_M:-null}"
TERMINATION_PENALTY_WEIGHT="${TERMINATION_PENALTY_WEIGHT:-0.0}"
MOTION_COMPLETION_BONUS_WEIGHT="${MOTION_COMPLETION_BONUS_WEIGHT:-0.0}"
EE_TERMINATION_PENALTY_WEIGHT="${EE_TERMINATION_PENALTY_WEIGHT:-0.0}"
FOOT_TERMINATION_PENALTY_WEIGHT="${FOOT_TERMINATION_PENALTY_WEIGHT:-0.0}"
EE_BODY_POS_RISK_WEIGHT="${EE_BODY_POS_RISK_WEIGHT:-0.0}"
EE_BODY_POS_RISK_ONSET="${EE_BODY_POS_RISK_ONSET:-0.10}"
FOOT_BODY_POS_RISK_WEIGHT="${FOOT_BODY_POS_RISK_WEIGHT:-0.0}"
FOOT_BODY_POS_RISK_ONSET="${FOOT_BODY_POS_RISK_ONSET:-0.14}"
ANCHOR_POS_RISK_WEIGHT="${ANCHOR_POS_RISK_WEIGHT:-0.0}"
ANCHOR_POS_RISK_ONSET="${ANCHOR_POS_RISK_ONSET:-0.10}"
ANCHOR_ORI_RISK_WEIGHT="${ANCHOR_ORI_RISK_WEIGHT:-0.0}"
ANCHOR_ORI_RISK_ONSET="${ANCHOR_ORI_RISK_ONSET:-0.10}"
CLAMP_NOISE_STD="${CLAMP_NOISE_STD:-false}"
MAX_NOISE_STD="${MAX_NOISE_STD:-0.18}"

ANCHOR_POS_XY_TERMINATION_OVERRIDES=()
if [[ "${ANCHOR_POS_XY_TERMINATION_ENABLED}" == "true" ]]; then
  ANCHOR_POS_XY_TERMINATION_OVERRIDES=(
    "++manager_env.terminations.anchor_pos_xy._target_=isaaclab.managers.TerminationTermCfg"
    "++manager_env.terminations.anchor_pos_xy.func=gear_sonic.envs.manager_env.mdp:exceeded_anchor_pos_xy"
    "++manager_env.terminations.anchor_pos_xy.params.command_name=motion"
    "++manager_env.terminations.anchor_pos_xy.params.threshold=${ANCHOR_POS_XY_THRESHOLD}"
  )
fi
ACTOR_LEARNING_RATE="${ACTOR_LEARNING_RATE:-2.0e-5}"
CRITIC_LEARNING_RATE="${CRITIC_LEARNING_RATE:-1.0e-3}"
PPO_LOSS_COEF="${PPO_LOSS_COEF:-1.0}"
ADAPTIVE_LR_MIN="${ADAPTIVE_LR_MIN:-1.0e-5}"
ADAPTIVE_LR_MAX="${ADAPTIVE_LR_MAX:-2.0e-4}"
ADAPTIVE_KL_FLOOR="${ADAPTIVE_KL_FLOOR:-1.0e-8}"
PPO_EPOCHS="${PPO_EPOCHS:-1}"
NUM_MINI_BATCHES="${NUM_MINI_BATCHES:-1}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-1}"
PPO_SHUFFLE_ENABLED="${PPO_SHUFFLE_ENABLED:-true}"
PPO_SHUFFLE_EVERY_EPOCH="${PPO_SHUFFLE_EVERY_EPOCH:-true}"
ALLOW_TF32="${ALLOW_TF32:-true}"
POLICY_REPLAY_MATCH_ROLLOUT="${POLICY_REPLAY_MATCH_ROLLOUT:-false}"
CRITIC_ONLY_BYPASS_ACTOR_REPLAY="${CRITIC_ONLY_BYPASS_ACTOR_REPLAY:-false}"
ACTOR_FEATURE_DELTA_REPLAY="${ACTOR_FEATURE_DELTA_REPLAY:-false}"
ACTOR_DECODER_DELTA_REPLAY="${ACTOR_DECODER_DELTA_REPLAY:-false}"
ACTUATOR_CONTEXT_RESIDUAL_GATE_ENABLED="${ACTUATOR_CONTEXT_RESIDUAL_GATE_ENABLED:-false}"
ACTUATOR_CONTEXT_RESIDUAL_GATE_TOLERANCE="${ACTUATOR_CONTEXT_RESIDUAL_GATE_TOLERANCE:-1.0e-6}"
TRAIN_ACTOR_LORA="${TRAIN_ACTOR_LORA:-true}"
TRAIN_CRITIC_LORA="${TRAIN_CRITIC_LORA:-true}"
TRAIN_BOUNDARY_KEYS="${TRAIN_BOUNDARY_KEYS:-[std]}"
SEPARATE_ACTOR_CRITIC_LR="${SEPARATE_ACTOR_CRITIC_LR:-false}"
PRESERVE_ADAPTIVE_OPTIMIZER_LR="${PRESERVE_ADAPTIVE_OPTIMIZER_LR:-false}"
TRAINING_DIAGNOSTICS_ENABLED="${TRAINING_DIAGNOSTICS_ENABLED:-false}"
CRITIC_HOLDOUT_EXPORT_ENABLED="${CRITIC_HOLDOUT_EXPORT_ENABLED:-false}"
GRADIENT_GEOMETRY_ENABLED="${GRADIENT_GEOMETRY_ENABLED:-false}"
GRADIENT_GEOMETRY_GROUPS_PATH="${GRADIENT_GEOMETRY_GROUPS_PATH:-null}"
GRADIENT_GEOMETRY_RESET_ENV_EACH_ITERATION="${GRADIENT_GEOMETRY_RESET_ENV_EACH_ITERATION:-false}"
ORACLE_ACTION_AUX_ENABLED="${ORACLE_ACTION_AUX_ENABLED:-false}"
ORACLE_ACTION_AUX_COEF="${ORACLE_ACTION_AUX_COEF:-0.0}"
ORACLE_ACTION_AUX_LOOKAHEAD_STEPS="${ORACLE_ACTION_AUX_LOOKAHEAD_STEPS:-6}"
ORACLE_ACTION_AUX_TARGET_SOURCE="${ORACLE_ACTION_AUX_TARGET_SOURCE:-reference_dof}"
ORACLE_ACTION_AUX_MAX_ABS_ACTION="${ORACLE_ACTION_AUX_MAX_ABS_ACTION:-20.0}"
ORACLE_ACTION_AUX_TOKENS="${ORACLE_ACTION_AUX_TOKENS:-[shoulder_,elbow_,wrist_]}"
ORACLE_ACTION_AUX_GRAD_DIAGNOSTICS="${ORACLE_ACTION_AUX_GRAD_DIAGNOSTICS:-false}"
ORACLE_ACTION_AUX_MODE="${ORACLE_ACTION_AUX_MODE:-absolute_mse}"
ORACLE_ACTION_AUX_PROJECTED_DELTA_LIMIT="${ORACLE_ACTION_AUX_PROJECTED_DELTA_LIMIT:-0.05}"
ORACLE_ACTION_AUX_TRANSITION_MULTIPLIER="${ORACLE_ACTION_AUX_TRANSITION_MULTIPLIER:-2.0}"
BALANCE_ORACLE_PROBE_ENABLED="${BALANCE_ORACLE_PROBE_ENABLED:-false}"
BALANCE_ORACLE_PREVIEW_FRAME_INDEX="${BALANCE_ORACLE_PREVIEW_FRAME_INDEX:-2}"
BALANCE_ORACLE_COM_GAIN="${BALANCE_ORACLE_COM_GAIN:-0.25}"
BALANCE_ORACLE_COM_VELOCITY_HORIZON_S="${BALANCE_ORACLE_COM_VELOCITY_HORIZON_S:-0.15}"
BALANCE_ORACLE_DAMPING="${BALANCE_ORACLE_DAMPING:-0.05}"
BALANCE_ORACLE_MAX_ABS_JOINT_DELTA_RAD="${BALANCE_ORACLE_MAX_ABS_JOINT_DELTA_RAD:-0.01}"
BALANCE_ORACLE_PREPARATION_SWING_LOAD_SHARE="${BALANCE_ORACLE_PREPARATION_SWING_LOAD_SHARE:-0.25}"
BALANCE_ORACLE_SINGLE_SUPPORT_SWING_LOAD_SHARE="${BALANCE_ORACLE_SINGLE_SUPPORT_SWING_LOAD_SHARE:-0.05}"
BALANCE_ORACLE_PREPARATION_ONLY="${BALANCE_ORACLE_PREPARATION_ONLY:-false}"
BALANCE_ORACLE_SOLVER_MODE="${BALANCE_ORACLE_SOLVER_MODE:-dls_position}"
BALANCE_ORACLE_VIRTUAL_FORCE_NATURAL_FREQUENCY_HZ="${BALANCE_ORACLE_VIRTUAL_FORCE_NATURAL_FREQUENCY_HZ:-0.5}"
BALANCE_ORACLE_VIRTUAL_FORCE_DAMPING_RATIO="${BALANCE_ORACLE_VIRTUAL_FORCE_DAMPING_RATIO:-1.0}"
BALANCE_ORACLE_ACTION_TOKENS="${BALANCE_ORACLE_ACTION_TOKENS:-[hip_roll_joint,ankle_roll_joint,waist_roll_joint]}"
DECOUPLED_LOCOMOTION_PROBE_ENABLED="${DECOUPLED_LOCOMOTION_PROBE_ENABLED:-false}"
DECOUPLED_LOCOMOTION_BALANCE_MODEL_PATH="${DECOUPLED_LOCOMOTION_BALANCE_MODEL_PATH:-${ROOT}/x2_sonic/sonic_x2_sandbox/decoupled_wbc/sim2mujoco/resources/robots/g1/policy/GR00T-WholeBodyControl-Balance.onnx}"
DECOUPLED_LOCOMOTION_WALK_MODEL_PATH="${DECOUPLED_LOCOMOTION_WALK_MODEL_PATH:-${ROOT}/x2_sonic/sonic_x2_sandbox/decoupled_wbc/sim2mujoco/resources/robots/g1/policy/GR00T-WholeBodyControl-Walk.onnx}"
DECOUPLED_LOCOMOTION_MODE="${DECOUPLED_LOCOMOTION_MODE:-balance}"
DECOUPLED_LOCOMOTION_RESIDUAL_SCALE_RAD="${DECOUPLED_LOCOMOTION_RESIDUAL_SCALE_RAD:-0.25}"
DECOUPLED_LOCOMOTION_HEIGHT_COMMAND_M="${DECOUPLED_LOCOMOTION_HEIGHT_COMMAND_M:-0.74}"
DECOUPLED_LOCOMOTION_REFERENCE_VELOCITY_GAIN="${DECOUPLED_LOCOMOTION_REFERENCE_VELOCITY_GAIN:-1.0}"
DECOUPLED_LOCOMOTION_MAX_COMMAND_X_MPS="${DECOUPLED_LOCOMOTION_MAX_COMMAND_X_MPS:-0.8}"
DECOUPLED_LOCOMOTION_MAX_COMMAND_Y_MPS="${DECOUPLED_LOCOMOTION_MAX_COMMAND_Y_MPS:-0.5}"
DECOUPLED_LOCOMOTION_MAX_COMMAND_YAW_RPS="${DECOUPLED_LOCOMOTION_MAX_COMMAND_YAW_RPS:-1.0}"
DECOUPLED_LOCOMOTION_HISTORY_LENGTH="${DECOUPLED_LOCOMOTION_HISTORY_LENGTH:-6}"
DECOUPLED_LOCOMOTION_AUTO_WALK_THRESHOLD="${DECOUPLED_LOCOMOTION_AUTO_WALK_THRESHOLD:-0.05}"
TWIST_TEACHER_PROBE_ENABLED="${TWIST_TEACHER_PROBE_ENABLED:-false}"
TWIST_TEACHER_MODEL_PATH="${TWIST_TEACHER_MODEL_PATH:-/home/humanplus/projects/agibot_x2_sdk/lx2501_3-v0.8.2.4/src/py_examples/py_examples/cap_twist/waist_dof_acc_track2_knee04_waistpitchchange_waistpitchpunish001_hipyawpunish01_taupunish2e5_new_stu-15000-jit.pt}"
TWIST_TEACHER_EXPECTED_SHA256="${TWIST_TEACHER_EXPECTED_SHA256:-a7c7ec4ea375a878988558c17fb53d746f45f7f76c552a144b8e7d05f0f755b2}"
TWIST_TEACHER_OWNERSHIP="${TWIST_TEACHER_OWNERSHIP:-full23}"
TWIST_TEACHER_RAW_ACTION_CLIP="${TWIST_TEACHER_RAW_ACTION_CLIP:-10.0}"
TWIST_TEACHER_ACTION_SCALE_RAD="${TWIST_TEACHER_ACTION_SCALE_RAD:-0.5}"
TWIST_TEACHER_REFERENCE_LOOKAHEAD_STEPS="${TWIST_TEACHER_REFERENCE_LOOKAHEAD_STEPS:-0}"
TWIST_TEACHER_CLAMP_TO_JOINT_LIMITS="${TWIST_TEACHER_CLAMP_TO_JOINT_LIMITS:-true}"
TWIST_TEACHER_MODE="${TWIST_TEACHER_MODE:-replace}"
TWIST_TEACHER_RESIDUAL_MAX_ABS_DELTA_RAD="${TWIST_TEACHER_RESIDUAL_MAX_ABS_DELTA_RAD:-0.02}"
TWIST_TEACHER_RESIDUAL_PREPARATION_ONLY="${TWIST_TEACHER_RESIDUAL_PREPARATION_ONLY:-true}"
TWIST_TEACHER_RESIDUAL_PREVIEW_FRAME_INDEX="${TWIST_TEACHER_RESIDUAL_PREVIEW_FRAME_INDEX:-9}"
TWIST_TEACHER_RESIDUAL_MIN_MOTION_STEP="${TWIST_TEACHER_RESIDUAL_MIN_MOTION_STEP:-0}"
TWIST_TEACHER_RESIDUAL_DIRECTION_FACTORS="${TWIST_TEACHER_RESIDUAL_DIRECTION_FACTORS:-[0.0,1.0,-1.0]}"
TWIST_TEACHER_RESIDUAL_ACTION_SOURCE_COPY_INDEX="${TWIST_TEACHER_RESIDUAL_ACTION_SOURCE_COPY_INDEX:-0}"
TWIST_TEACHER_RESIDUAL_DIRECTION_FACTOR="${TWIST_TEACHER_RESIDUAL_DIRECTION_FACTOR:-1.0}"
TWIST_TEACHER_RESIDUAL_BASIS="${TWIST_TEACHER_RESIDUAL_BASIS:-stance_hip_roll}"
TWIST_TEACHER_RESIDUAL_HOLD_STEPS="${TWIST_TEACHER_RESIDUAL_HOLD_STEPS:-1}"
TWIST_TEACHER_SEQUENCE_FIRST_BASIS="${TWIST_TEACHER_SEQUENCE_FIRST_BASIS:-stance_hip_roll+waist_roll}"
TWIST_TEACHER_SEQUENCE_SECOND_BASIS="${TWIST_TEACHER_SEQUENCE_SECOND_BASIS:-stance_hip_pitch_forward}"
TWIST_TEACHER_SEQUENCE_FIRST_STEPS="${TWIST_TEACHER_SEQUENCE_FIRST_STEPS:-5}"
TWIST_TEACHER_SEQUENCE_SECOND_STEPS="${TWIST_TEACHER_SEQUENCE_SECOND_STEPS:-5}"
TWIST_TEACHER_SEQUENCE_FIRST_DELTA_RAD="${TWIST_TEACHER_SEQUENCE_FIRST_DELTA_RAD:-${TWIST_TEACHER_RESIDUAL_MAX_ABS_DELTA_RAD}}"
TWIST_TEACHER_SEQUENCE_SECOND_DELTA_RAD="${TWIST_TEACHER_SEQUENCE_SECOND_DELTA_RAD:-${TWIST_TEACHER_RESIDUAL_MAX_ABS_DELTA_RAD}}"
TWIST_TEACHER_SEQUENCE_FEEDBACK_MODE="${TWIST_TEACHER_SEQUENCE_FEEDBACK_MODE:-none}"
TWIST_TEACHER_SEQUENCE_FEEDBACK_POSITION_NORMALIZER_M="${TWIST_TEACHER_SEQUENCE_FEEDBACK_POSITION_NORMALIZER_M:-0.10}"
TWIST_TEACHER_SEQUENCE_FEEDBACK_MIN_SCALE="${TWIST_TEACHER_SEQUENCE_FEEDBACK_MIN_SCALE:-0.25}"
TWIST_TEACHER_SEQUENCE_FEEDBACK_MAX_SCALE="${TWIST_TEACHER_SEQUENCE_FEEDBACK_MAX_SCALE:-2.0}"
TWIST_TEACHER_SPLINE_HORIZON_STEPS="${TWIST_TEACHER_SPLINE_HORIZON_STEPS:-10}"
TWIST_TEACHER_SPLINE_HIP_ROLL_KNOTS_RAD="${TWIST_TEACHER_SPLINE_HIP_ROLL_KNOTS_RAD:-[0.0,0.0,0.0]}"
TWIST_TEACHER_SPLINE_WAIST_ROLL_KNOTS_RAD="${TWIST_TEACHER_SPLINE_WAIST_ROLL_KNOTS_RAD:-[0.0,0.0,0.0]}"
TWIST_TEACHER_SPLINE_STANCE_HIP_PITCH_FORWARD_KNOTS_RAD="${TWIST_TEACHER_SPLINE_STANCE_HIP_PITCH_FORWARD_KNOTS_RAD:-[0.0,0.0,0.0]}"
TWIST_TEACHER_SPLINE_SWING_KNEE_KNOTS_RAD="${TWIST_TEACHER_SPLINE_SWING_KNEE_KNOTS_RAD:-[0.0,0.0,0.0]}"
TWIST_TEACHER_SPLINE_SWING_ANKLE_PITCH_KNOTS_RAD="${TWIST_TEACHER_SPLINE_SWING_ANKLE_PITCH_KNOTS_RAD:-[0.0,0.0,0.0]}"
SOURCE_RETENTION_ENABLED="${SOURCE_RETENTION_ENABLED:-false}"
SOURCE_RETENTION_ACTION_COEF="${SOURCE_RETENTION_ACTION_COEF:-1.0}"
SOURCE_RETENTION_LORA_COEF="${SOURCE_RETENTION_LORA_COEF:-0.001}"
SOURCE_RETENTION_ACTION_TOLERANCE="${SOURCE_RETENTION_ACTION_TOLERANCE:-1.0}"
SOURCE_RETENTION_LORA_TOLERANCE="${SOURCE_RETENTION_LORA_TOLERANCE:-1.0}"
SOURCE_RETENTION_FIXED_REPLAY_ENABLED="${SOURCE_RETENTION_FIXED_REPLAY_ENABLED:-false}"
SOURCE_RETENTION_FIXED_REPLAY_COEF="${SOURCE_RETENTION_FIXED_REPLAY_COEF:-0.0}"
SOURCE_RETENTION_FIXED_REPLAY_TOLERANCE="${SOURCE_RETENTION_FIXED_REPLAY_TOLERANCE:-1.0}"
SOURCE_RETENTION_FIXED_REPLAY_PHASE_BALANCED="${SOURCE_RETENTION_FIXED_REPLAY_PHASE_BALANCED:-false}"
SOURCE_RETENTION_FIXED_REPLAY_TRANSITION_MULTIPLIER="${SOURCE_RETENTION_FIXED_REPLAY_TRANSITION_MULTIPLIER:-2.0}"
SOURCE_RETENTION_REFERENCE_MODE="${SOURCE_RETENTION_REFERENCE_MODE:-frozen_base}"
SOURCE_RETENTION_LOWER_BODY_MULT="${SOURCE_RETENTION_LOWER_BODY_MULT:-1.0}"
SOURCE_RETENTION_INCLUDED_TOKENS="${SOURCE_RETENTION_INCLUDED_TOKENS:-[]}"
SOURCE_RETENTION_IDEAL_CONTEXT_ONLY="${SOURCE_RETENTION_IDEAL_CONTEXT_ONLY:-false}"
SOURCE_RETENTION_IDEAL_CONTEXT_TOLERANCE="${SOURCE_RETENTION_IDEAL_CONTEXT_TOLERANCE:-1.0e-6}"
GATE_AWARE_RETENTION_ENABLED="${GATE_AWARE_RETENTION_ENABLED:-false}"
GATE_AWARE_ROOT_METRIC="${GATE_AWARE_ROOT_METRIC:-anchor_pos}"
GATE_AWARE_ROOT_ONSET="${GATE_AWARE_ROOT_ONSET:-0.075}"
GATE_AWARE_ROOT_THRESHOLD="${GATE_AWARE_ROOT_THRESHOLD:-0.15}"
GATE_AWARE_MAX_MULTIPLIER="${GATE_AWARE_MAX_MULTIPLIER:-10.0}"
GATE_AWARE_EE_RETENTION_ENABLED="${GATE_AWARE_EE_RETENTION_ENABLED:-false}"
GATE_AWARE_EE_ONSET="${GATE_AWARE_EE_ONSET:-0.10}"
GATE_AWARE_EE_THRESHOLD="${GATE_AWARE_EE_THRESHOLD:-0.15}"
GATE_AWARE_EE_MAX_MULTIPLIER="${GATE_AWARE_EE_MAX_MULTIPLIER:-10.0}"
GATE_AWARE_EE_EXPONENT="${GATE_AWARE_EE_EXPONENT:-2.0}"
GATE_AWARE_EE_BODY_NAMES="${GATE_AWARE_EE_BODY_NAMES:-[left_wrist_yaw_link,right_wrist_yaw_link]}"
GATE_AWARE_FOOT_RETENTION_ENABLED="${GATE_AWARE_FOOT_RETENTION_ENABLED:-false}"
GATE_AWARE_FOOT_ONSET="${GATE_AWARE_FOOT_ONSET:-0.14}"
GATE_AWARE_FOOT_THRESHOLD="${GATE_AWARE_FOOT_THRESHOLD:-0.20}"
GATE_AWARE_FOOT_MAX_MULTIPLIER="${GATE_AWARE_FOOT_MAX_MULTIPLIER:-10.0}"
GATE_AWARE_FOOT_EXPONENT="${GATE_AWARE_FOOT_EXPONENT:-2.0}"
GATE_AWARE_FOOT_BODY_NAMES="${GATE_AWARE_FOOT_BODY_NAMES:-[left_ankle_roll_link,right_ankle_roll_link]}"
GATE_AWARE_RISK_COMBINE_MODE="${GATE_AWARE_RISK_COMBINE_MODE:-max}"
PRESERVE_LORA_CHECKPOINT="${PRESERVE_LORA_CHECKPOINT:-false}"
STACK_LORA_CHECKPOINT_RESIDUAL="${STACK_LORA_CHECKPOINT_RESIDUAL:-false}"
PRESERVE_APPENDED_CRITIC_FEATURES="${PRESERVE_APPENDED_CRITIC_FEATURES:-false}"
SEMANTIC_NEUTRAL_INIT_UNMAPPED="${SEMANTIC_NEUTRAL_INIT_UNMAPPED:-false}"
SEMANTIC_COPY_STRICT="${SEMANTIC_COPY_STRICT:-true}"
RUNTIME_RESIDUAL_BLEND_ENABLED="${RUNTIME_RESIDUAL_BLEND_ENABLED:-false}"
RUNTIME_BLEND_ROOT_ENABLED="${RUNTIME_BLEND_ROOT_ENABLED:-true}"
RUNTIME_BLEND_ROOT_ONSET="${RUNTIME_BLEND_ROOT_ONSET:-0.10}"
RUNTIME_BLEND_ROOT_THRESHOLD="${RUNTIME_BLEND_ROOT_THRESHOLD:-0.15}"
RUNTIME_BLEND_EE_ENABLED="${RUNTIME_BLEND_EE_ENABLED:-false}"
RUNTIME_BLEND_EE_ONSET="${RUNTIME_BLEND_EE_ONSET:-0.10}"
RUNTIME_BLEND_EE_THRESHOLD="${RUNTIME_BLEND_EE_THRESHOLD:-0.15}"
RUNTIME_BLEND_EE_BODY_NAMES="${RUNTIME_BLEND_EE_BODY_NAMES:-[left_wrist_yaw_link,right_wrist_yaw_link]}"
RUNTIME_BLEND_EE_SIDE_SPECIFIC="${RUNTIME_BLEND_EE_SIDE_SPECIFIC:-false}"
RUNTIME_BLEND_EE_ACTION_TOKENS="${RUNTIME_BLEND_EE_ACTION_TOKENS:-[]}"
RUNTIME_BLEND_FOOT_ENABLED="${RUNTIME_BLEND_FOOT_ENABLED:-false}"
RUNTIME_BLEND_FOOT_ONSET="${RUNTIME_BLEND_FOOT_ONSET:-0.14}"
RUNTIME_BLEND_FOOT_THRESHOLD="${RUNTIME_BLEND_FOOT_THRESHOLD:-0.20}"
RUNTIME_BLEND_FOOT_BODY_NAMES="${RUNTIME_BLEND_FOOT_BODY_NAMES:-[left_ankle_roll_link,right_ankle_roll_link]}"
RUNTIME_BLEND_FOOT_SIDE_SPECIFIC="${RUNTIME_BLEND_FOOT_SIDE_SPECIFIC:-false}"
RUNTIME_BLEND_FOOT_ACTION_TOKENS="${RUNTIME_BLEND_FOOT_ACTION_TOKENS:-[]}"
RUNTIME_BLEND_MIN_GATE="${RUNTIME_BLEND_MIN_GATE:-0.0}"
RUNTIME_BLEND_MAX_GATE="${RUNTIME_BLEND_MAX_GATE:-1.0}"
RUNTIME_BLEND_EXPONENT="${RUNTIME_BLEND_EXPONENT:-2.0}"
RUNTIME_BLEND_PASSTHROUGH_TOKENS="${RUNTIME_BLEND_PASSTHROUGH_TOKENS:-[]}"
RUNTIME_BLEND_PASSTHROUGH_GATE="${RUNTIME_BLEND_PASSTHROUGH_GATE:-1.0}"
ACTOR_LORA_PREFIXES="${ACTOR_LORA_PREFIXES:-[actor_module.decoders.g1_dyn]}"
ACTOR_INPUT_MASK_ENABLED="${ACTOR_INPUT_MASK_ENABLED:-false}"
ACTOR_INPUT_MASK_LAYERS="${ACTOR_INPUT_MASK_LAYERS:-[actor_module.decoders.g1_dyn.module.0]}"
ACTOR_INPUT_MASK_DECODER="${ACTOR_INPUT_MASK_DECODER:-g1_dyn}"
ACTOR_INPUT_MASK_FEATURES="${ACTOR_INPUT_MASK_FEATURES:-[command_multi_future_foot_contacts]}"
ACTOR_OUTPUT_MASK_ENABLED="${ACTOR_OUTPUT_MASK_ENABLED:-false}"
ACTOR_OUTPUT_MASK_LAYERS="${ACTOR_OUTPUT_MASK_LAYERS:-[actor_module.decoders.g1_dyn.module.12]}"
ACTOR_OUTPUT_MASK_TOKENS="${ACTOR_OUTPUT_MASK_TOKENS:-[shoulder_,elbow_,wrist_]}"
ACTOR_OUTPUT_UNSELECTED_SCALE="${ACTOR_OUTPUT_UNSELECTED_SCALE:-0.0}"
ACTOR_OUTPUT_AUX_TOKENS="${ACTOR_OUTPUT_AUX_TOKENS:-[]}"
ACTOR_OUTPUT_AUX_SCALE="${ACTOR_OUTPUT_AUX_SCALE:-0.0}"
ACTOR_DECODER_ACTION_PROJECTION_ENABLED="${ACTOR_DECODER_ACTION_PROJECTION_ENABLED:-false}"
ACTOR_DECODER_ACTION_PROJECTION_DECODER="${ACTOR_DECODER_ACTION_PROJECTION_DECODER:-g1_dyn}"
RESPONSE_AWARE_LORA_ENABLED="${RESPONSE_AWARE_LORA_ENABLED:-false}"
RESPONSE_AWARE_LORA_LAYERS="${RESPONSE_AWARE_LORA_LAYERS:-[actor_module.decoders.g1_dyn.module.12]}"
RESPONSE_AWARE_INPUT_SCALE="${RESPONSE_AWARE_INPUT_SCALE:-1.0}"
RESPONSE_AWARE_HIDDEN_DIM="${RESPONSE_AWARE_HIDDEN_DIM:-64}"
RESPONSE_AWARE_MAX_CONDITION="${RESPONSE_AWARE_MAX_CONDITION:-1.0}"
RESPONSE_AWARE_HISTORY_LENGTH="${RESPONSE_AWARE_HISTORY_LENGTH:-4}"
RESPONSE_AWARE_JOINT_COUNT="${RESPONSE_AWARE_JOINT_COUNT:-29}"
RESPONSE_AWARE_TARGET_POSITION_SCALE="${RESPONSE_AWARE_TARGET_POSITION_SCALE:-1.0}"
RESPONSE_AWARE_JOINT_POSITION_SCALE="${RESPONSE_AWARE_JOINT_POSITION_SCALE:-1.0}"
RESPONSE_AWARE_JOINT_VELOCITY_SCALE="${RESPONSE_AWARE_JOINT_VELOCITY_SCALE:-0.1}"
RESPONSE_AWARE_TRACKING_ERROR_SCALE="${RESPONSE_AWARE_TRACKING_ERROR_SCALE:-1.0}"
RESPONSE_AWARE_JOINT_INCLUDE_TOKENS="${RESPONSE_AWARE_JOINT_INCLUDE_TOKENS:-[]}"
RESPONSE_AWARE_OUTPUT_ACTION_TOKENS="${RESPONSE_AWARE_OUTPUT_ACTION_TOKENS:-[]}"
RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR="${RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR:-false}"
RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE="${RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE:-10.0}"
RESPONSE_AWARE_TRAIN_RESPONSE_ONLY="${RESPONSE_AWARE_TRAIN_RESPONSE_ONLY:-false}"
PRETRAIN_EXPORT_PATH="${PRETRAIN_EXPORT_PATH:-null}"
DETERMINISTIC_ROLLOUT="${DETERMINISTIC_ROLLOUT:-false}"
TRAIN_WITH_EVALUATING_ENV="${TRAIN_WITH_EVALUATING_ENV:-false}"
PAIRED_ACTION_ROUTER_ENABLED="${PAIRED_ACTION_ROUTER_ENABLED:-false}"
PAIRED_ACTION_ROUTER_MODE="${PAIRED_ACTION_ROUTER_MODE:-counterfactual_nominal_shifted_lower}"
PAIRED_ACTION_ROUTER_SOURCE_ENV_INDEX="${PAIRED_ACTION_ROUTER_SOURCE_ENV_INDEX:-0}"
PAIRED_ACTION_ROUTER_TARGET_ENV_INDEX="${PAIRED_ACTION_ROUTER_TARGET_ENV_INDEX:-1}"
PAIRED_ACTION_ROUTER_MIRROR_BLEND="${PAIRED_ACTION_ROUTER_MIRROR_BLEND:-0.5}"
PAIRED_ACTION_ROUTER_LOWER_BODY_TOKENS="${PAIRED_ACTION_ROUTER_LOWER_BODY_TOKENS:-[hip_,knee_joint,ankle_]}"
X2_SEMANTIC_COUNTERFACTUAL_ENABLED="${X2_SEMANTIC_COUNTERFACTUAL_ENABLED:-false}"
X2_SEMANTIC_COUNTERFACTUAL_MODES="${X2_SEMANTIC_COUNTERFACTUAL_MODES:-[semantic_mirror,contact_swap,contact_lead2,contact_lag2,contact_reverse,contact_double_support]}"
X2_SEMANTIC_COUNTERFACTUAL_MAX_STEPS="${X2_SEMANTIC_COUNTERFACTUAL_MAX_STEPS:-null}"
TRAIN_ONLY_EVENTS="${TRAIN_ONLY_EVENTS:-[]}"
CLEAN_EVAL="${CLEAN_EVAL:-false}"
EVAL_OBSERVATION_CORRUPTION="${EVAL_OBSERVATION_CORRUPTION:-false}"
CLEAN_COMMAND_INIT="${CLEAN_COMMAND_INIT:-false}"
ENCODER_SAMPLE_PROBS="${ENCODER_SAMPLE_PROBS:-}"
SOURCE_CANONICAL_REFERENCE="${SOURCE_CANONICAL_REFERENCE:-false}"
FIX_BASE="${FIX_BASE:-false}"
UPPER_BODY_ONLY_ACTION="${UPPER_BODY_ONLY_ACTION:-false}"
X2_PD_PROFILE="${X2_PD_PROFILE:-natural_frequency}"
X2_COLLISION_PROFILE="${X2_COLLISION_PROFILE:-mesh}"
X2_SELF_COLLISIONS="${X2_SELF_COLLISIONS:-true}"
X2_ACTION_SCALE_PROFILE="${X2_ACTION_SCALE_PROFILE:-torque_normalized}"
SIM_DT="${SIM_DT:-0.005}"
DECIMATION="${DECIMATION:-4}"
SAVE_FREQUENCY="${SAVE_FREQUENCY:-2000}"
SAVE_LAST_FREQUENCY="${SAVE_LAST_FREQUENCY:-50}"
TOTAL_EPISODES=$((NUM_ENVS * ITERS))
RUN_LOG_DIR="${LOG_ROOT}/${RUN_NAME}"
CONSOLE_LOG="${RUN_LOG_DIR}/console.log"
WRIST_TRACE="${RUN_LOG_DIR}/x2_wrist_rollout_trace.jsonl"
TRAINING_DIAGNOSTICS_PATH="${RUN_LOG_DIR}/training_diagnostics.jsonl"
X2_SEMANTIC_COUNTERFACTUAL_OUTPUT_PATH="${X2_SEMANTIC_COUNTERFACTUAL_OUTPUT_PATH:-${RUN_LOG_DIR}/x2_semantic_counterfactual.jsonl}"
CRITIC_HOLDOUT_EXPORT_PATH="${CRITIC_HOLDOUT_EXPORT_PATH:-${RUN_LOG_DIR}/critic_holdout.pt}"
GRADIENT_GEOMETRY_OUTPUT_PATH="${GRADIENT_GEOMETRY_OUTPUT_PATH:-${RUN_LOG_DIR}/gradient_geometry.pt}"
CONSTRAINT_GRADIENT_GEOMETRY_ENABLED="${CONSTRAINT_GRADIENT_GEOMETRY_ENABLED:-false}"
CONSTRAINT_GRADIENT_GEOMETRY_OUTPUT_PATH="${CONSTRAINT_GRADIENT_GEOMETRY_OUTPUT_PATH:-${RUN_LOG_DIR}/constraint_gradient_geometry.pt}"
CONSTRAINT_ROOT_POS_TOLERANCE="${CONSTRAINT_ROOT_POS_TOLERANCE:-0.10}"
CONSTRAINT_ROOT_ORI_TOLERANCE="${CONSTRAINT_ROOT_ORI_TOLERANCE:-0.25}"
CONSTRAINT_LEFT_WRIST_TOLERANCE="${CONSTRAINT_LEFT_WRIST_TOLERANCE:-0.35}"
CONSTRAINT_RIGHT_WRIST_TOLERANCE="${CONSTRAINT_RIGHT_WRIST_TOLERANCE:-0.35}"
CONSTRAINT_FOOT_TOLERANCE="${CONSTRAINT_FOOT_TOLERANCE:-0.20}"
CONSTRAINT_WAIST_TOLERANCE="${CONSTRAINT_WAIST_TOLERANCE:-0.30}"
CONSTRAINT_OPTIMIZATION_ENABLED="${CONSTRAINT_OPTIMIZATION_ENABLED:-false}"
CONSTRAINT_OPTIMIZATION_HISTORY_PATH="${CONSTRAINT_OPTIMIZATION_HISTORY_PATH:-${RUN_LOG_DIR}/constraint_optimization_history.jsonl}"
CONSTRAINT_DUAL_LEARNING_RATE="${CONSTRAINT_DUAL_LEARNING_RATE:-0.05}"
CONSTRAINT_INITIAL_MULTIPLIER="${CONSTRAINT_INITIAL_MULTIPLIER:-0.05}"
CONSTRAINT_MAX_MULTIPLIER="${CONSTRAINT_MAX_MULTIPLIER:-1.0}"
CONSTRAINT_ROOT_POS_MAX_MULTIPLIER="${CONSTRAINT_ROOT_POS_MAX_MULTIPLIER:-${CONSTRAINT_MAX_MULTIPLIER}}"
CONSTRAINT_ROOT_ORI_MAX_MULTIPLIER="${CONSTRAINT_ROOT_ORI_MAX_MULTIPLIER:-${CONSTRAINT_MAX_MULTIPLIER}}"
CONSTRAINT_LEFT_WRIST_MAX_MULTIPLIER="${CONSTRAINT_LEFT_WRIST_MAX_MULTIPLIER:-${CONSTRAINT_MAX_MULTIPLIER}}"
CONSTRAINT_RIGHT_WRIST_MAX_MULTIPLIER="${CONSTRAINT_RIGHT_WRIST_MAX_MULTIPLIER:-${CONSTRAINT_MAX_MULTIPLIER}}"
CONSTRAINT_FOOT_MAX_MULTIPLIER="${CONSTRAINT_FOOT_MAX_MULTIPLIER:-${CONSTRAINT_MAX_MULTIPLIER}}"
CONSTRAINT_WAIST_MAX_MULTIPLIER="${CONSTRAINT_WAIST_MAX_MULTIPLIER:-${CONSTRAINT_MAX_MULTIPLIER}}"
CONSTRAINT_DUAL_UPDATE_MODE="${CONSTRAINT_DUAL_UPDATE_MODE:-absolute}"
CONSTRAINT_RISK_MODE="${CONSTRAINT_RISK_MODE:-mean}"
CONSTRAINT_RISK_QUANTILE="${CONSTRAINT_RISK_QUANTILE:-0.95}"
CONSTRAINT_SURROGATE_TAIL_QUANTILE="${CONSTRAINT_SURROGATE_TAIL_QUANTILE:-null}"
CONSTRAINT_MOTION_BALANCED="${CONSTRAINT_MOTION_BALANCED:-false}"
CONSTRAINT_MOTION_RISK_REDUCTION="${CONSTRAINT_MOTION_RISK_REDUCTION:-mean}"
CONSTRAINT_MOTION_RISK_TOP_FRACTION="${CONSTRAINT_MOTION_RISK_TOP_FRACTION:-0.25}"
CONSTRAINT_MOTION_EQUAL_SURROGATE="${CONSTRAINT_MOTION_EQUAL_SURROGATE:-false}"
CONSTRAINT_LORA_ANCHOR_COEF="${CONSTRAINT_LORA_ANCHOR_COEF:-0.01}"
CONSTRAINT_LORA_ANCHOR_TOLERANCE="${CONSTRAINT_LORA_ANCHOR_TOLERANCE:-0.001}"
CONSTRAINT_ROOT_POS_BUDGET="${CONSTRAINT_ROOT_POS_BUDGET:-1.15}"
CONSTRAINT_ROOT_ORI_BUDGET="${CONSTRAINT_ROOT_ORI_BUDGET:-0.62}"
CONSTRAINT_LEFT_WRIST_BUDGET="${CONSTRAINT_LEFT_WRIST_BUDGET:-0.19}"
CONSTRAINT_RIGHT_WRIST_BUDGET="${CONSTRAINT_RIGHT_WRIST_BUDGET:-0.16}"
CONSTRAINT_FOOT_BUDGET="${CONSTRAINT_FOOT_BUDGET:-0.31}"
CONSTRAINT_WAIST_BUDGET="${CONSTRAINT_WAIST_BUDGET:-0.27}"

case "${ACTUATOR_RESPONSE_MODE}" in
  off)
    ACTUATOR_RESPONSE_ENABLED=false
    ACTUATOR_RESPONSE_RANDOMIZE=false
    ;;
  session02_nominal)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=false
    ACTUATOR_RESPONSE_PROFILE="session02_group"
    ;;
  session02_randomized)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=true
    ACTUATOR_RESPONSE_PROFILE="session02_group"
    ;;
  session03_nominal)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=false
    ACTUATOR_RESPONSE_PROFILE="session03_group"
    ;;
  session03_randomized)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=true
    ACTUATOR_RESPONSE_PROFILE="session03_group"
    ;;
  session03_mixed)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=true
    ACTUATOR_RESPONSE_PROFILE="session03_group"
    ACTUATOR_RESPONSE_INCLUDE_IDEAL=true
    ACTUATOR_RESPONSE_IDEAL_FRACTION="${ACTUATOR_RESPONSE_IDEAL_FRACTION:-0.25}"
    ;;
  session0304_nominal)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=false
    ACTUATOR_RESPONSE_PROFILE="session03_session04_group"
    ;;
  session0304_filter_only)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=false
    ACTUATOR_RESPONSE_PROFILE="session03_session04_group"
    ACTUATOR_RESPONSE_DELAY_STRENGTH=0.0
    ACTUATOR_RESPONSE_FILTER_STRENGTH=1.0
    ;;
  session0304_randomized)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=true
    ACTUATOR_RESPONSE_PROFILE="session03_session04_group"
    ;;
  session0304_mixed)
    ACTUATOR_RESPONSE_ENABLED=true
    ACTUATOR_RESPONSE_RANDOMIZE=true
    ACTUATOR_RESPONSE_PROFILE="session03_session04_group"
    ACTUATOR_RESPONSE_INCLUDE_IDEAL=true
    ACTUATOR_RESPONSE_IDEAL_FRACTION="${ACTUATOR_RESPONSE_IDEAL_FRACTION:-0.25}"
    ;;
  *)
    echo "unsupported ACTUATOR_RESPONSE_MODE=${ACTUATOR_RESPONSE_MODE}" >&2
    exit 2
    ;;
esac
ACTUATOR_RESPONSE_IDEAL_FRACTION="${ACTUATOR_RESPONSE_IDEAL_FRACTION:-0.0}"
ACTUATOR_RESPONSE_DELAY_STRENGTH="${ACTUATOR_RESPONSE_DELAY_STRENGTH:-${ACTUATOR_RESPONSE_STRENGTH}}"
ACTUATOR_RESPONSE_FILTER_STRENGTH="${ACTUATOR_RESPONSE_FILTER_STRENGTH:-${ACTUATOR_RESPONSE_STRENGTH}}"

case "${REWARD_WRIST_LINK}" in
  yaw) REWARD_WRIST_LEFT=left_wrist_yaw_link; REWARD_WRIST_RIGHT=right_wrist_yaw_link ;;
  roll) REWARD_WRIST_LEFT=left_wrist_roll_link; REWARD_WRIST_RIGHT=right_wrist_roll_link ;;
  *)
    echo "unsupported REWARD_WRIST_LINK=${REWARD_WRIST_LINK}" >&2
    exit 2
    ;;
esac

case "${REWARD_POINT_MODE}" in
  source3)
    REWARD_POINT_BODY_NAMES="[torso_link,${REWARD_WRIST_LEFT},${REWARD_WRIST_RIGHT}]"
    REWARD_POINT_BODY_OFFSETS='[[0.0,0.0,0.5],[0.0,0.0,0.0],[0.0,0.0,0.0]]'
    ;;
  x2_5point)
    REWARD_POINT_BODY_NAMES="[base_link,${REWARD_WRIST_LEFT},${REWARD_WRIST_RIGHT},left_ankle_roll_link,right_ankle_roll_link]"
    REWARD_POINT_BODY_OFFSETS='[[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.0]]'
    ;;
  *)
    echo "unsupported REWARD_POINT_MODE=${REWARD_POINT_MODE}" >&2
    exit 2
    ;;
esac

case "${TRACKED_BODY_SET}" in
  source14)
    TRACKED_BODY_NAMES='[base_link,left_hip_roll_link,left_knee_link,left_ankle_roll_link,right_hip_roll_link,right_knee_link,right_ankle_roll_link,torso_link,left_shoulder_roll_link,left_elbow_link,left_wrist_roll_link,right_shoulder_roll_link,right_elbow_link,right_wrist_roll_link]'
    ;;
  x2_full33)
    TRACKED_BODY_NAMES='[base_link,left_hip_pitch_link,right_hip_pitch_link,waist_yaw_link,left_hip_roll_link,right_hip_roll_link,waist_pitch_link,left_hip_yaw_link,right_hip_yaw_link,torso_link,left_knee_link,right_knee_link,head_yaw_link,left_shoulder_pitch_link,right_shoulder_pitch_link,left_ankle_pitch_link,right_ankle_pitch_link,head_pitch_link,left_shoulder_roll_link,right_shoulder_roll_link,left_ankle_roll_link,right_ankle_roll_link,left_shoulder_yaw_link,right_shoulder_yaw_link,left_elbow_link,right_elbow_link,left_wrist_yaw_link,right_wrist_yaw_link,left_wrist_pitch_link,right_wrist_pitch_link,left_wrist_roll_link,right_wrist_roll_link]'
    ;;
  *)
    echo "unsupported TRACKED_BODY_SET=${TRACKED_BODY_SET}" >&2
    exit 2
    ;;
esac

case "${ACTUATOR_GAIN_RANDOMIZATION}" in
  off)
    ACTUATOR_GAIN_EVENT_OVERRIDE='manager_env.events.randomize_actuator_gains=null'
    ;;
  on)
    ACTUATOR_GAIN_EVENT_OVERRIDE='manager_env.events.randomize_actuator_gains.mode=startup'
    ;;
  *)
    echo "unsupported ACTUATOR_GAIN_RANDOMIZATION=${ACTUATOR_GAIN_RANDOMIZATION}" >&2
    exit 2
    ;;
esac

case "${CLEAN_EVAL}" in
  false)
    CLEAN_EVAL_OVERRIDES=()
    RIGID_BODY_MASS_EVENT_OVERRIDE="manager_env.events.randomize_rigid_body_mass.params.mass_distribution_params=${RIGID_BODY_MASS_RANGE}"
    ;;
  true)
    # train_agent_trl.py does not consume manager_env.config.train_only_events;
    # remove every stochastic event before environment construction and turn
    # off policy/critic observation corruption explicitly.
    CLEAN_EVAL_OVERRIDES=(
      'manager_env.events.physics_material=null'
      'manager_env.events.add_joint_default_pos=null'
      'manager_env.events.base_com=null'
      'manager_env.events.push_robot=null'
      "manager_env.observations.policy.enable_corruption=${EVAL_OBSERVATION_CORRUPTION}"
      "manager_env.observations.tokenizer.enable_corruption=${EVAL_OBSERVATION_CORRUPTION}"
    )
    RIGID_BODY_MASS_EVENT_OVERRIDE='manager_env.events.randomize_rigid_body_mass=null'
    ;;
  *)
    echo "unsupported CLEAN_EVAL=${CLEAN_EVAL}" >&2
    exit 2
    ;;
esac

case "${EVAL_OBSERVATION_CORRUPTION}" in
  true|false) ;;
  *)
    echo "unsupported EVAL_OBSERVATION_CORRUPTION=${EVAL_OBSERVATION_CORRUPTION}" >&2
    exit 2
    ;;
esac

case "${CLEAN_COMMAND_INIT}" in
  false)
    COMMAND_INIT_OVERRIDES=()
    ;;
  true)
    # Controlled embodiment/response curricula need the ideal and response
    # halves to begin from the same reference state.  This is independent of
    # CLEAN_EVAL because train_agent_trl keeps command reset randomization on.
    COMMAND_INIT_OVERRIDES=(
      'manager_env.commands.motion.pose_range={x:[0.0,0.0],y:[0.0,0.0],z:[0.0,0.0],roll:[0.0,0.0],pitch:[0.0,0.0],yaw:[0.0,0.0]}'
      'manager_env.commands.motion.velocity_range={x:[0.0,0.0],y:[0.0,0.0],z:[0.0,0.0],roll:[0.0,0.0],pitch:[0.0,0.0],yaw:[0.0,0.0]}'
      'manager_env.commands.motion.joint_position_range=[0.0,0.0]'
      'manager_env.commands.motion.joint_velocity_range=[0.0,0.0]'
    )
    ;;
  *)
    echo "unsupported CLEAN_COMMAND_INIT=${CLEAN_COMMAND_INIT}" >&2
    exit 2
    ;;
esac

if [[ -n "${ENCODER_SAMPLE_PROBS}" ]]; then
  ENCODER_SAMPLE_OVERRIDE=(
    "manager_env.commands.motion.encoder_sample_probs=${ENCODER_SAMPLE_PROBS}"
    "algo.config.actor.backbone.encoder_sample_probs=${ENCODER_SAMPLE_PROBS}"
  )
else
  ENCODER_SAMPLE_OVERRIDE=()
fi

case "${SOURCE_CANONICAL_REFERENCE}" in
  false) SOURCE_CANONICAL_OVERRIDES=() ;;
  true)
    SOURCE_CANONICAL_OVERRIDES=(
      'manager_env.observations.tokenizer.command_multi_future_nonflat.func=gear_sonic.envs.manager_env.mdp:command_multi_future_source_canonical'
      'manager_env.observations.tokenizer.command_multi_future_lower_body.func=gear_sonic.envs.manager_env.mdp:command_multi_future_lower_body_source_canonical'
    )
    ;;
  *) echo "unsupported SOURCE_CANONICAL_REFERENCE=${SOURCE_CANONICAL_REFERENCE}" >&2; exit 2 ;;
esac

case "${VR_WRIST_OFFSET_MODE}" in
  current)
    VR_3POINT_OFFSETS='[[0.18,-0.025,0.0],[0.18,0.025,0.0],[0.0,0.0,0.35]]'
    ;;
  zero)
    VR_3POINT_OFFSETS='[[0.0,0.0,0.0],[0.0,0.0,0.0],[0.0,0.0,0.35]]'
    ;;
  *)
    echo "unsupported VR_WRIST_OFFSET_MODE=${VR_WRIST_OFFSET_MODE}" >&2
    exit 2
    ;;
esac

case "${EE_WRIST_LINK}" in
  yaw)
    EE_BODY_NAMES='[left_ankle_roll_link,right_ankle_roll_link,left_wrist_yaw_link,right_wrist_yaw_link]'
    EE_HEIGHT_BODY_NAMES='[left_wrist_yaw_link,right_wrist_yaw_link]'
    ;;
  roll)
    EE_BODY_NAMES='[left_ankle_roll_link,right_ankle_roll_link,left_wrist_roll_link,right_wrist_roll_link]'
    EE_HEIGHT_BODY_NAMES='[left_wrist_roll_link,right_wrist_roll_link]'
    ;;
  both)
    EE_BODY_NAMES='[left_ankle_roll_link,right_ankle_roll_link,left_wrist_yaw_link,right_wrist_yaw_link,left_wrist_roll_link,right_wrist_roll_link]'
    EE_HEIGHT_BODY_NAMES='[left_wrist_yaw_link,right_wrist_yaw_link,left_wrist_roll_link,right_wrist_roll_link]'
    ;;
  *)
    echo "unsupported EE_WRIST_LINK=${EE_WRIST_LINK}" >&2
    exit 2
    ;;
esac

mkdir -p "${RUN_LOG_DIR}"
cd "${SANDBOX}"

set +e
{
echo "x2_sonic_lora_smoke_start=$(date -Is)"
echo "run_name=${RUN_NAME}"
echo "run_kind=${RUN_KIND}"
echo "clean_eval=${CLEAN_EVAL}"
echo "clean_command_init=${CLEAN_COMMAND_INIT}"
echo "encoder_sample_probs=${ENCODER_SAMPLE_PROBS:-task_default}"
echo "source_canonical_reference=${SOURCE_CANONICAL_REFERENCE}"
echo "fixed_base=${FIX_BASE}"
echo "upper_body_only_action=${UPPER_BODY_ONLY_ACTION}"
echo "x2_pd_profile=${X2_PD_PROFILE}"
echo "x2_collision_profile=${X2_COLLISION_PROFILE}"
echo "x2_self_collisions=${X2_SELF_COLLISIONS}"
echo "x2_action_scale_profile=${X2_ACTION_SCALE_PROFILE}"
echo "simulation_timing=sim_dt:${SIM_DT},decimation:${DECIMATION},control_dt:$(awk -v dt="${SIM_DT}" -v dec="${DECIMATION}" 'BEGIN { printf "%.9f", dt * dec }')"
echo "resume=${RESUME}"
echo "resume_keep_experiment_dir=${RESUME_KEEP_EXPERIMENT_DIR}"
echo "seed=${SEED}"
echo "num_envs=${NUM_ENVS} steps_per_env=${STEPS_PER_ENV} iters=${ITERS} motions=${MOTIONS}"
echo "dcpeft_num_critics=${NUM_CRITICS} reward_contract=${DCPEFT_REWARD_CONTRACT:-none} advantage_weights=${MULTI_CRITIC_ADVANTAGE_WEIGHTS}"
echo "terrain_type=${TERRAIN_TYPE}"
echo "action_scale_mult=${ACTION_SCALE_MULT}"
echo "action_scale_joint_multipliers=${ACTION_SCALE_JOINT_MULTIPLIERS}"
echo "actuator_response_mode=${ACTUATOR_RESPONSE_MODE}"
echo "actuator_response_profile=${ACTUATOR_RESPONSE_PROFILE}"
echo "actuator_response_strength=${ACTUATOR_RESPONSE_STRENGTH}"
echo "actuator_response_delay_strength=${ACTUATOR_RESPONSE_DELAY_STRENGTH}"
echo "actuator_response_filter_strength=${ACTUATOR_RESPONSE_FILTER_STRENGTH}"
echo "actuator_response_include_ideal=${ACTUATOR_RESPONSE_INCLUDE_IDEAL}"
echo "actuator_response_ideal_fraction=${ACTUATOR_RESPONSE_IDEAL_FRACTION}"
echo "actuator_response_context_override=${ACTUATOR_RESPONSE_CONTEXT_OVERRIDE}"
echo "action_preemphasis=enabled:${ACTION_PREEMPHASIS_ENABLED},strength:${ACTION_PREEMPHASIS_STRENGTH},max_delta_rad:${ACTION_PREEMPHASIS_MAX_DELTA_RAD},groups:${ACTION_PREEMPHASIS_GROUPS}"
echo "actuator_gain_randomization=${ACTUATOR_GAIN_RANDOMIZATION}"
echo "eval_observation_corruption=${EVAL_OBSERVATION_CORRUPTION}"
echo "rigid_body_mass_range=${RIGID_BODY_MASS_RANGE}"
echo "vr_wrist_offset_mode=${VR_WRIST_OFFSET_MODE} vr_3point_offsets=${VR_3POINT_OFFSETS}"
echo "ee_wrist_link=${EE_WRIST_LINK} ee_body_names=${EE_BODY_NAMES}"
echo "reward_wrist_link=${REWARD_WRIST_LINK} reward_point_mode=${REWARD_POINT_MODE} reward_point_body=${REWARD_POINT_BODY_NAMES}"
echo "tracked_body_set=${TRACKED_BODY_SET} tracked_body_names=${TRACKED_BODY_NAMES}"
echo "anti_shake_body_names=${ANTI_SHAKE_BODY_NAMES}"
echo "wrist_diagnostics=${WRIST_DIAGNOSTICS} wrist_trace=${WRIST_TRACE}"
echo "render_results=${RENDER_RESULTS},recorders:${RENDER_RECORDERS},size:${RENDER_WIDTH}x${RENDER_HEIGHT},skip:${RENDER_FRAME_SKIP},max_envs:${MAX_RENDER_ENVS}"
echo "termination_thresholds=anchor_pos:${ANCHOR_POS_THRESHOLD},anchor_ori_full:${ANCHOR_ORI_FULL_THRESHOLD},ee_body_pos:${EE_BODY_POS_THRESHOLD},foot_pos_xyz:${FOOT_POS_XYZ_THRESHOLD}"
echo "anchor_pos_xy_termination=enabled:${ANCHOR_POS_XY_TERMINATION_ENABLED},threshold:${ANCHOR_POS_XY_THRESHOLD}"
echo "vr_tracking_reward_weight=${VR_TRACKING_REWARD_WEIGHT}"
echo "ee_height_reward=weight:${EE_HEIGHT_REWARD_WEIGHT},std:${EE_HEIGHT_REWARD_STD},bodies:${EE_HEIGHT_BODY_NAMES}"
echo "anchor_pos_reward=weight:${ANCHOR_POS_REWARD_WEIGHT},std:${ANCHOR_POS_REWARD_STD}"
echo "anchor_linvel_reward=weight:${ANCHOR_LINVEL_REWARD_WEIGHT},std:${ANCHOR_LINVEL_REWARD_STD},horizontal_only:true"
echo "anchor_path_penalty=weight:${ANCHOR_PATH_ERROR_WEIGHT},along_tol:${ANCHOR_PATH_ALONG_TOLERANCE_M},cross_tol:${ANCHOR_PATH_CROSS_TOLERANCE_M},along_norm:${ANCHOR_PATH_ALONG_NORMALIZATION_M},cross_norm:${ANCHOR_PATH_CROSS_NORMALIZATION_M},min_length:${ANCHOR_PATH_MIN_LENGTH_M}"
echo "anchor_ori_reward_weight=${ANCHOR_ORI_REWARD_WEIGHT}"
echo "relative_body_pos_reward_weight=${RELATIVE_BODY_POS_REWARD_WEIGHT}"
echo "single_support_tracking_relaxation=preview:${SINGLE_SUPPORT_TRACKING_PREPARATION_FUTURE_FRAME_INDEX},anchor_lateral:${SINGLE_SUPPORT_ANCHOR_LATERAL_SCALE},stance_body:${SINGLE_SUPPORT_STANCE_BODY_SCALE},stance_foot:${SINGLE_SUPPORT_STANCE_FOOT_SCALE}"
echo "stability_reward_weights=joint_limit:${JOINT_LIMIT_REWARD_WEIGHT},feet_acc:${FEET_ACC_REWARD_WEIGHT}"
echo "foot_contact_phase_reward=weight:${FOOT_CONTACT_PHASE_REWARD_WEIGHT},force_threshold:${FOOT_CONTACT_FORCE_THRESHOLD},costs:${FOOT_CONTACT_SWING_CONTACT_COST}/${FOOT_CONTACT_MISSED_STANCE_COST},swing_scales:${FOOT_CONTACT_LEFT_SWING_COST_SCALE}/${FOOT_CONTACT_RIGHT_SWING_COST_SCALE},continuous_load:${FOOT_CONTACT_CONTINUOUS_LOAD},continuous_load_mode:${FOOT_CONTACT_CONTINUOUS_LOAD_MODE},swing_force_normalizer:${FOOT_CONTACT_SWING_FORCE_NORMALIZER},support_force_fraction_of_weight:${FOOT_CONTACT_SUPPORT_FORCE_FRACTION_OF_WEIGHT},preparation_future_frame_index:${FOOT_CONTACT_PREPARATION_FUTURE_FRAME_INDEX},preparation_preserve_double_contact:${FOOT_CONTACT_PREPARATION_PRESERVE_DOUBLE_CONTACT}"
echo "swing_foot_height_reward=weight:${SWING_FOOT_HEIGHT_REWARD_WEIGHT},std:${SWING_FOOT_HEIGHT_REWARD_STD}"
echo "single_support_com_reward=weight:${SINGLE_SUPPORT_COM_REWARD_WEIGHT},normalization_m:${SINGLE_SUPPORT_COM_NORMALIZATION_M},preparation_future_frame_index:${SINGLE_SUPPORT_COM_PREPARATION_FUTURE_FRAME_INDEX}"
echo "reference_stance_foot_slip_reward=weight:${REFERENCE_STANCE_FOOT_SLIP_REWARD_WEIGHT},normalization_mps:${REFERENCE_STANCE_FOOT_SLIP_NORMALIZATION_MPS}"
echo "interfoot_relative_pos_reward=weight:${INTERFOOT_RELATIVE_POS_REWARD_WEIGHT},std:${INTERFOOT_RELATIVE_POS_REWARD_STD}"
echo "foot_contact_labels=mode:${FOOT_CONTACT_LABEL_MODE},ground_percentile:${FOOT_CONTACT_GROUND_PERCENTILE},height_margin_m:${FOOT_CONTACT_HEIGHT_MARGIN_M},vertical_speed_max_mps:${FOOT_CONTACT_VERTICAL_SPEED_MAX_MPS},max_ground_band_m:${FOOT_CONTACT_MAX_GROUND_BAND_M}"
echo "selected_joint_tracking=weight:${SELECTED_JOINT_TRACKING_REWARD_WEIGHT},std:${SELECTED_JOINT_TRACKING_REWARD_STD},joints:${SELECTED_JOINT_TRACKING_NAMES}"
echo "termination_penalty_weight=${TERMINATION_PENALTY_WEIGHT}"
echo "motion_completion_bonus_weight=${MOTION_COMPLETION_BONUS_WEIGHT}"
echo "ee_termination_penalty_weight=${EE_TERMINATION_PENALTY_WEIGHT}"
echo "foot_termination_penalty_weight=${FOOT_TERMINATION_PENALTY_WEIGHT}"
echo "ee_body_pos_risk=weight:${EE_BODY_POS_RISK_WEIGHT},onset:${EE_BODY_POS_RISK_ONSET},threshold:${EE_BODY_POS_THRESHOLD}"
echo "foot_body_pos_risk=weight:${FOOT_BODY_POS_RISK_WEIGHT},onset:${FOOT_BODY_POS_RISK_ONSET},threshold:${FOOT_POS_XYZ_THRESHOLD}"
echo "anchor_pos_risk=weight:${ANCHOR_POS_RISK_WEIGHT},onset:${ANCHOR_POS_RISK_ONSET},threshold:${ANCHOR_POS_THRESHOLD}"
echo "anchor_ori_risk=weight:${ANCHOR_ORI_RISK_WEIGHT},onset:${ANCHOR_ORI_RISK_ONSET},threshold:${ANCHOR_ORI_FULL_THRESHOLD}"
echo "exploration_noise=clamp:${CLAMP_NOISE_STD},max_std:${MAX_NOISE_STD}"
echo "motion_file=${MOTION_FILE}"
echo "adaptive_sampling_enabled=${ADAPTIVE_SAMPLING_ENABLED}"
echo "paired_motions=${USE_PAIRED_MOTIONS} start_from_first_frame=${START_FROM_FIRST_FRAME} paired_start_mode_pattern=${PAIRED_START_MODE_PATTERN} preserve_auto_reset_frame_zero=${PRESERVE_AUTO_RESET_FRAME_ZERO} freeze_frame_aug=${FREEZE_FRAME_AUG}"
echo "contact_phase_sync=enabled:${CONTACT_PHASE_SYNC_ENABLED},lead:${CONTACT_PHASE_SYNC_LEAD_STEPS},lag:${CONTACT_PHASE_SYNC_LAG_STEPS},max_advance:${CONTACT_PHASE_SYNC_MAX_ADVANCE_PER_STEP},force_threshold:${CONTACT_PHASE_SYNC_FORCE_THRESHOLD}"
echo "contact_load_gate=enabled:${CONTACT_LOAD_GATE_ENABLED},preview:${CONTACT_LOAD_GATE_PREVIEW_STEPS},max_hold:${CONTACT_LOAD_GATE_MAX_HOLD_STEPS},stance_share:${CONTACT_LOAD_GATE_MIN_STANCE_SHARE},min_total_load_n:${CONTACT_LOAD_GATE_MIN_TOTAL_LOAD_N}"
echo "lower_body_reference_delay_steps=${LOWER_BODY_REFERENCE_DELAY_STEPS}"
echo "exp_config=${EXP_CONFIG} train_only_events=${TRAIN_ONLY_EVENTS}"
echo "checkpoint=${CHECKPOINT}"
echo "actor_learning_rate=${ACTOR_LEARNING_RATE} critic_learning_rate=${CRITIC_LEARNING_RATE} ppo_loss_coef=${PPO_LOSS_COEF} separate_actor_critic_lr=${SEPARATE_ACTOR_CRITIC_LR} adaptive_lr=[${ADAPTIVE_LR_MIN},${ADAPTIVE_LR_MAX}] adaptive_kl_floor=${ADAPTIVE_KL_FLOOR} preserve_adaptive_optimizer_lr=${PRESERVE_ADAPTIVE_OPTIMIZER_LR} ppo_epochs=${PPO_EPOCHS} num_mini_batches=${NUM_MINI_BATCHES} gradient_accumulation_steps=${GRADIENT_ACCUMULATION_STEPS} ppo_shuffle_enabled=${PPO_SHUFFLE_ENABLED} ppo_shuffle_every_epoch=${PPO_SHUFFLE_EVERY_EPOCH} deterministic_rollout=${DETERMINISTIC_ROLLOUT} train_with_evaluating_env=${TRAIN_WITH_EVALUATING_ENV} save_frequency=${SAVE_FREQUENCY} save_last_frequency=${SAVE_LAST_FREQUENCY}"
echo "lora_train_actor=${TRAIN_ACTOR_LORA} lora_train_critic=${TRAIN_CRITIC_LORA} train_boundary_keys=${TRAIN_BOUNDARY_KEYS} allow_tf32=${ALLOW_TF32} policy_replay_match_rollout=${POLICY_REPLAY_MATCH_ROLLOUT} critic_only_bypass_actor_replay=${CRITIC_ONLY_BYPASS_ACTOR_REPLAY} actor_feature_delta_replay=${ACTOR_FEATURE_DELTA_REPLAY} actor_decoder_delta_replay=${ACTOR_DECODER_DELTA_REPLAY} training_diagnostics=${TRAINING_DIAGNOSTICS_ENABLED}:${TRAINING_DIAGNOSTICS_PATH}"
echo "x2_semantic_counterfactual=${X2_SEMANTIC_COUNTERFACTUAL_ENABLED}:${X2_SEMANTIC_COUNTERFACTUAL_OUTPUT_PATH},modes:${X2_SEMANTIC_COUNTERFACTUAL_MODES},max_steps:${X2_SEMANTIC_COUNTERFACTUAL_MAX_STEPS}"
echo "actuator_context_residual_gate=enabled:${ACTUATOR_CONTEXT_RESIDUAL_GATE_ENABLED},ideal_tolerance:${ACTUATOR_CONTEXT_RESIDUAL_GATE_TOLERANCE}"
echo "critic_holdout_export=${CRITIC_HOLDOUT_EXPORT_ENABLED}:${CRITIC_HOLDOUT_EXPORT_PATH}"
echo "gradient_geometry=${GRADIENT_GEOMETRY_ENABLED}:${GRADIENT_GEOMETRY_OUTPUT_PATH},groups:${GRADIENT_GEOMETRY_GROUPS_PATH},reset_each_iteration:${GRADIENT_GEOMETRY_RESET_ENV_EACH_ITERATION}"
echo "constraint_gradient_geometry=${CONSTRAINT_GRADIENT_GEOMETRY_ENABLED}:${CONSTRAINT_GRADIENT_GEOMETRY_OUTPUT_PATH},tol:${CONSTRAINT_ROOT_POS_TOLERANCE}/${CONSTRAINT_ROOT_ORI_TOLERANCE}/${CONSTRAINT_LEFT_WRIST_TOLERANCE}/${CONSTRAINT_RIGHT_WRIST_TOLERANCE}/${CONSTRAINT_FOOT_TOLERANCE}/${CONSTRAINT_WAIST_TOLERANCE}"
echo "constraint_optimization=${CONSTRAINT_OPTIMIZATION_ENABLED},dual_lr:${CONSTRAINT_DUAL_LEARNING_RATE},dual_mode:${CONSTRAINT_DUAL_UPDATE_MODE},lambda:${CONSTRAINT_INITIAL_MULTIPLIER},max:${CONSTRAINT_ROOT_POS_MAX_MULTIPLIER}/${CONSTRAINT_ROOT_ORI_MAX_MULTIPLIER}/${CONSTRAINT_LEFT_WRIST_MAX_MULTIPLIER}/${CONSTRAINT_RIGHT_WRIST_MAX_MULTIPLIER}/${CONSTRAINT_FOOT_MAX_MULTIPLIER}/${CONSTRAINT_WAIST_MAX_MULTIPLIER},risk:${CONSTRAINT_RISK_MODE}@${CONSTRAINT_RISK_QUANTILE},tail:${CONSTRAINT_SURROGATE_TAIL_QUANTILE},motion_balanced:${CONSTRAINT_MOTION_BALANCED},motion_reduction:${CONSTRAINT_MOTION_RISK_REDUCTION}@${CONSTRAINT_MOTION_RISK_TOP_FRACTION},motion_equal_surrogate:${CONSTRAINT_MOTION_EQUAL_SURROGATE},anchor:${CONSTRAINT_LORA_ANCHOR_COEF}@${CONSTRAINT_LORA_ANCHOR_TOLERANCE},budgets:${CONSTRAINT_ROOT_POS_BUDGET}/${CONSTRAINT_ROOT_ORI_BUDGET}/${CONSTRAINT_LEFT_WRIST_BUDGET}/${CONSTRAINT_RIGHT_WRIST_BUDGET}/${CONSTRAINT_FOOT_BUDGET}/${CONSTRAINT_WAIST_BUDGET}"
echo "oracle_action_aux=enabled:${ORACLE_ACTION_AUX_ENABLED},coef:${ORACLE_ACTION_AUX_COEF},lookahead_steps:${ORACLE_ACTION_AUX_LOOKAHEAD_STEPS},target_source:${ORACLE_ACTION_AUX_TARGET_SOURCE},max_abs_action:${ORACLE_ACTION_AUX_MAX_ABS_ACTION},tokens:${ORACLE_ACTION_AUX_TOKENS},gradient_diagnostics:${ORACLE_ACTION_AUX_GRAD_DIAGNOSTICS},mode:${ORACLE_ACTION_AUX_MODE},projected_delta_limit:${ORACLE_ACTION_AUX_PROJECTED_DELTA_LIMIT},transition_multiplier:${ORACLE_ACTION_AUX_TRANSITION_MULTIPLIER}"
echo "balance_oracle_probe=enabled:${BALANCE_ORACLE_PROBE_ENABLED},preview:${BALANCE_ORACLE_PREVIEW_FRAME_INDEX},com_gain:${BALANCE_ORACLE_COM_GAIN},velocity_horizon:${BALANCE_ORACLE_COM_VELOCITY_HORIZON_S},damping:${BALANCE_ORACLE_DAMPING},max_joint_delta_rad:${BALANCE_ORACLE_MAX_ABS_JOINT_DELTA_RAD},load_share:${BALANCE_ORACLE_PREPARATION_SWING_LOAD_SHARE}/${BALANCE_ORACLE_SINGLE_SUPPORT_SWING_LOAD_SHARE},preparation_only:${BALANCE_ORACLE_PREPARATION_ONLY},solver:${BALANCE_ORACLE_SOLVER_MODE},force_frequency:${BALANCE_ORACLE_VIRTUAL_FORCE_NATURAL_FREQUENCY_HZ},force_damping:${BALANCE_ORACLE_VIRTUAL_FORCE_DAMPING_RATIO},tokens:${BALANCE_ORACLE_ACTION_TOKENS}"
echo "decoupled_locomotion_probe=enabled:${DECOUPLED_LOCOMOTION_PROBE_ENABLED},mode:${DECOUPLED_LOCOMOTION_MODE},balance:${DECOUPLED_LOCOMOTION_BALANCE_MODEL_PATH},walk:${DECOUPLED_LOCOMOTION_WALK_MODEL_PATH},residual_scale_rad:${DECOUPLED_LOCOMOTION_RESIDUAL_SCALE_RAD},height_m:${DECOUPLED_LOCOMOTION_HEIGHT_COMMAND_M},velocity_gain:${DECOUPLED_LOCOMOTION_REFERENCE_VELOCITY_GAIN},command_limits:${DECOUPLED_LOCOMOTION_MAX_COMMAND_X_MPS}/${DECOUPLED_LOCOMOTION_MAX_COMMAND_Y_MPS}/${DECOUPLED_LOCOMOTION_MAX_COMMAND_YAW_RPS},history:${DECOUPLED_LOCOMOTION_HISTORY_LENGTH},auto_threshold:${DECOUPLED_LOCOMOTION_AUTO_WALK_THRESHOLD}"
echo "twist_teacher_probe=enabled:${TWIST_TEACHER_PROBE_ENABLED},mode:${TWIST_TEACHER_MODE},ownership:${TWIST_TEACHER_OWNERSHIP},model:${TWIST_TEACHER_MODEL_PATH},sha256:${TWIST_TEACHER_EXPECTED_SHA256},raw_clip:${TWIST_TEACHER_RAW_ACTION_CLIP},action_scale_rad:${TWIST_TEACHER_ACTION_SCALE_RAD},reference_lookahead_steps:${TWIST_TEACHER_REFERENCE_LOOKAHEAD_STEPS},clamp_to_joint_limits:${TWIST_TEACHER_CLAMP_TO_JOINT_LIMITS},preview_frame_index:${TWIST_TEACHER_RESIDUAL_PREVIEW_FRAME_INDEX},min_motion_step:${TWIST_TEACHER_RESIDUAL_MIN_MOTION_STEP},direction_factors:${TWIST_TEACHER_RESIDUAL_DIRECTION_FACTORS},direction_factor:${TWIST_TEACHER_RESIDUAL_DIRECTION_FACTOR},basis:${TWIST_TEACHER_RESIDUAL_BASIS},hold_steps:${TWIST_TEACHER_RESIDUAL_HOLD_STEPS},source_copy:${TWIST_TEACHER_RESIDUAL_ACTION_SOURCE_COPY_INDEX}"
echo "source_policy_retention=enabled:${SOURCE_RETENTION_ENABLED},action_mean_coef:${SOURCE_RETENTION_ACTION_COEF},lora_weight_coef:${SOURCE_RETENTION_LORA_COEF},action_mean_tolerance:${SOURCE_RETENTION_ACTION_TOLERANCE},lora_weight_tolerance:${SOURCE_RETENTION_LORA_TOLERANCE},fixed_replay:${SOURCE_RETENTION_FIXED_REPLAY_ENABLED}@${SOURCE_RETENTION_FIXED_REPLAY_COEF}/${SOURCE_RETENTION_FIXED_REPLAY_TOLERANCE},fixed_phase_balance:${SOURCE_RETENTION_FIXED_REPLAY_PHASE_BALANCED}@${SOURCE_RETENTION_FIXED_REPLAY_TRANSITION_MULTIPLIER},reference_mode:${SOURCE_RETENTION_REFERENCE_MODE},lower_body_multiplier:${SOURCE_RETENTION_LOWER_BODY_MULT},included_tokens:${SOURCE_RETENTION_INCLUDED_TOKENS},ideal_context_only:${SOURCE_RETENTION_IDEAL_CONTEXT_ONLY}@${SOURCE_RETENTION_IDEAL_CONTEXT_TOLERANCE},excluded:[head_yaw_joint,head_pitch_joint]"
echo "gate_aware_retention=enabled:${GATE_AWARE_RETENTION_ENABLED},root_metric:${GATE_AWARE_ROOT_METRIC},root_onset:${GATE_AWARE_ROOT_ONSET},root_threshold:${GATE_AWARE_ROOT_THRESHOLD},max_multiplier:${GATE_AWARE_MAX_MULTIPLIER},ee_enabled:${GATE_AWARE_EE_RETENTION_ENABLED},ee_onset:${GATE_AWARE_EE_ONSET},ee_threshold:${GATE_AWARE_EE_THRESHOLD},ee_max_multiplier:${GATE_AWARE_EE_MAX_MULTIPLIER},ee_exponent:${GATE_AWARE_EE_EXPONENT},ee_bodies:${GATE_AWARE_EE_BODY_NAMES},foot_enabled:${GATE_AWARE_FOOT_RETENTION_ENABLED},foot_onset:${GATE_AWARE_FOOT_ONSET},foot_threshold:${GATE_AWARE_FOOT_THRESHOLD},foot_max_multiplier:${GATE_AWARE_FOOT_MAX_MULTIPLIER},foot_exponent:${GATE_AWARE_FOOT_EXPONENT},foot_bodies:${GATE_AWARE_FOOT_BODY_NAMES},combine_mode:${GATE_AWARE_RISK_COMBINE_MODE}"
echo "lora_checkpoint_preserve_residual=${PRESERVE_LORA_CHECKPOINT}"
echo "lora_checkpoint_stack_residual=${STACK_LORA_CHECKPOINT_RESIDUAL}"
echo "lora_checkpoint_preserve_appended_critic_features=${PRESERVE_APPENDED_CRITIC_FEATURES}"
echo "semantic_neutral_init_unmapped=${SEMANTIC_NEUTRAL_INIT_UNMAPPED}"
echo "semantic_copy_strict=${SEMANTIC_COPY_STRICT}"
echo "runtime_residual_blend=enabled:${RUNTIME_RESIDUAL_BLEND_ENABLED},root_enabled:${RUNTIME_BLEND_ROOT_ENABLED},root_onset:${RUNTIME_BLEND_ROOT_ONSET},root_threshold:${RUNTIME_BLEND_ROOT_THRESHOLD},ee_enabled:${RUNTIME_BLEND_EE_ENABLED},ee_onset:${RUNTIME_BLEND_EE_ONSET},ee_threshold:${RUNTIME_BLEND_EE_THRESHOLD},ee_bodies:${RUNTIME_BLEND_EE_BODY_NAMES},ee_side_specific:${RUNTIME_BLEND_EE_SIDE_SPECIFIC},ee_action_tokens:${RUNTIME_BLEND_EE_ACTION_TOKENS},foot_enabled:${RUNTIME_BLEND_FOOT_ENABLED},foot_onset:${RUNTIME_BLEND_FOOT_ONSET},foot_threshold:${RUNTIME_BLEND_FOOT_THRESHOLD},foot_bodies:${RUNTIME_BLEND_FOOT_BODY_NAMES},foot_side_specific:${RUNTIME_BLEND_FOOT_SIDE_SPECIFIC},foot_action_tokens:${RUNTIME_BLEND_FOOT_ACTION_TOKENS},gate_range:[${RUNTIME_BLEND_MIN_GATE},${RUNTIME_BLEND_MAX_GATE}],exponent:${RUNTIME_BLEND_EXPONENT},passthrough_tokens:${RUNTIME_BLEND_PASSTHROUGH_TOKENS},passthrough_gate:${RUNTIME_BLEND_PASSTHROUGH_GATE}"
echo "actor_lora_prefixes=${ACTOR_LORA_PREFIXES}"
echo "actor_input_mask=enabled:${ACTOR_INPUT_MASK_ENABLED},layers:${ACTOR_INPUT_MASK_LAYERS},decoder:${ACTOR_INPUT_MASK_DECODER},features:${ACTOR_INPUT_MASK_FEATURES}"
echo "actor_output_mask=enabled:${ACTOR_OUTPUT_MASK_ENABLED},layers:${ACTOR_OUTPUT_MASK_LAYERS},tokens:${ACTOR_OUTPUT_MASK_TOKENS},aux_tokens:${ACTOR_OUTPUT_AUX_TOKENS},aux_scale:${ACTOR_OUTPUT_AUX_SCALE},unselected_scale:${ACTOR_OUTPUT_UNSELECTED_SCALE},excluded:[head_yaw_joint,head_pitch_joint]"
echo "response_aware_lora=enabled:${RESPONSE_AWARE_LORA_ENABLED},layers:${RESPONSE_AWARE_LORA_LAYERS},input_scale:${RESPONSE_AWARE_INPUT_SCALE},hidden_dim:${RESPONSE_AWARE_HIDDEN_DIM},max_condition:${RESPONSE_AWARE_MAX_CONDITION},history:${RESPONSE_AWARE_HISTORY_LENGTH}x${RESPONSE_AWARE_JOINT_COUNT},component_scales:${RESPONSE_AWARE_TARGET_POSITION_SCALE}/${RESPONSE_AWARE_JOINT_POSITION_SCALE}/${RESPONSE_AWARE_JOINT_VELOCITY_SCALE}/${RESPONSE_AWARE_TRACKING_ERROR_SCALE},input_tokens:${RESPONSE_AWARE_JOINT_INCLUDE_TOKENS},output_tokens:${RESPONSE_AWARE_OUTPUT_ACTION_TOKENS},contact_error_gate:${RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR}@${RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE},response_only:${RESPONSE_AWARE_TRAIN_RESPONSE_ONLY}"
echo "actor_decoder_action_projection=enabled:${ACTOR_DECODER_ACTION_PROJECTION_ENABLED},decoder:${ACTOR_DECODER_ACTION_PROJECTION_DECODER}"
echo "pretrain_export_path=${PRETRAIN_EXPORT_PATH}"

timeout "${TIMEOUT_SECONDS:-600}s" env \
  OMNI_KIT_ACCEPT_EULA=YES \
  ACCEPT_EULA=Y \
  PYTHONPATH="${PROJECT_ROOT}/src:${PYTHONPATH:-}" \
  DCPEFT_REWARD_CONTRACT="${DCPEFT_REWARD_CONTRACT}" \
  DCPEFT_REWARD_AUDIT_JSONL="${DCPEFT_REWARD_AUDIT_JSONL}" \
  conda run --no-capture-output -n x2-sonic-isaaclab \
  python train_agent_trl.py \
  "+exp=${EXP_CONFIG}" \
  "+checkpoint=${CHECKPOINT}" \
  +allow_tf32="${ALLOW_TF32}" \
  seed="${SEED}" \
  num_envs="${NUM_ENVS}" \
  headless=True \
  use_wandb=False \
  project_name=X2_SONIC_LORA_SMOKE \
  experiment_name="${RUN_NAME}" \
  +resume="${RESUME}" \
  +resume_keep_experiment_dir="${RESUME_KEEP_EXPERIMENT_DIR}" \
  base_dir="${LOG_ROOT}" \
  experiment_dir="${LOG_ROOT}/${RUN_NAME}" \
  hydra.run.dir="${LOG_ROOT}/hydra_${RUN_NAME}" \
  manager_env.config.terrain_type="${TERRAIN_TYPE}" \
  manager_env.config.sim_dt="${SIM_DT}" \
  manager_env.config.decimation="${DECIMATION}" \
  "+manager_env.config.action_scale_mult=${ACTION_SCALE_MULT}" \
  "manager_env.config.rewards.num_critics=${NUM_CRITICS}" \
  "algo.config.critic.backbone.module_config_dict.output_dim=[${NUM_CRITICS}]" \
  "+algo.config.multi_critic_advantage_weights=${MULTI_CRITIC_ADVANTAGE_WEIGHTS}" \
  "+manager_env.config.action_scale_joint_multipliers=${ACTION_SCALE_JOINT_MULTIPLIERS}" \
  "+manager_env.config.fixed_base=${FIX_BASE}" \
  "+manager_env.config.upper_body_only_action=${UPPER_BODY_ONLY_ACTION}" \
  "+manager_env.config.x2_pd_profile=${X2_PD_PROFILE}" \
  "+manager_env.config.x2_collision_profile=${X2_COLLISION_PROFILE}" \
  +manager_env.config.x2_enabled_self_collisions="${X2_SELF_COLLISIONS}" \
  "+manager_env.config.x2_action_scale_profile=${X2_ACTION_SCALE_PROFILE}" \
  "+manager_env.config.x2_actuator_response.enabled=${ACTUATOR_RESPONSE_ENABLED}" \
  "+manager_env.config.x2_actuator_response.profile=${ACTUATOR_RESPONSE_PROFILE}" \
  "+manager_env.config.x2_actuator_response.randomize=${ACTUATOR_RESPONSE_RANDOMIZE}" \
  "+manager_env.config.x2_actuator_response.include_ideal_endpoint=${ACTUATOR_RESPONSE_INCLUDE_IDEAL}" \
  "+manager_env.config.x2_actuator_response.strength=${ACTUATOR_RESPONSE_STRENGTH}" \
  "+manager_env.config.x2_actuator_response.delay_strength=${ACTUATOR_RESPONSE_DELAY_STRENGTH}" \
  "+manager_env.config.x2_actuator_response.filter_strength=${ACTUATOR_RESPONSE_FILTER_STRENGTH}" \
  "+manager_env.config.x2_actuator_response.ideal_env_fraction=${ACTUATOR_RESPONSE_IDEAL_FRACTION}" \
  "+manager_env.config.x2_action_preemphasis.enabled=${ACTION_PREEMPHASIS_ENABLED}" \
  "+manager_env.config.x2_action_preemphasis.strength=${ACTION_PREEMPHASIS_STRENGTH}" \
  "+manager_env.config.x2_action_preemphasis.max_abs_delta_rad=${ACTION_PREEMPHASIS_MAX_DELTA_RAD}" \
  "+manager_env.config.x2_action_preemphasis.actuator_group_names=${ACTION_PREEMPHASIS_GROUPS}" \
  "+manager_env.config.x2_action_preemphasis.require_response_actuator=true" \
  "manager_env.observations.policy.x2_actuator_response_context.params.fixed_context=${ACTUATOR_RESPONSE_CONTEXT_OVERRIDE}" \
  "${ACTUATOR_GAIN_EVENT_OVERRIDE}" \
  "${RIGID_BODY_MASS_EVENT_OVERRIDE}" \
  "${CLEAN_EVAL_OVERRIDES[@]}" \
  "${COMMAND_INIT_OVERRIDES[@]}" \
  "${ENCODER_SAMPLE_OVERRIDE[@]}" \
  "${SOURCE_CANONICAL_OVERRIDES[@]}" \
  "${ANCHOR_POS_XY_TERMINATION_OVERRIDES[@]}" \
  manager_env.terminations.anchor_pos.params.threshold="${ANCHOR_POS_THRESHOLD}" \
  manager_env.terminations.anchor_ori_full.params.threshold="${ANCHOR_ORI_FULL_THRESHOLD}" \
  manager_env.terminations.ee_body_pos.params.threshold="${EE_BODY_POS_THRESHOLD}" \
  "manager_env.terminations.ee_body_pos.params.body_names=${EE_BODY_NAMES}" \
  manager_env.terminations.foot_pos_xyz.params.threshold="${FOOT_POS_XYZ_THRESHOLD}" \
  manager_env.rewards.tracking_vr_5point_local.weight="${VR_TRACKING_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_ee_height.weight="${EE_HEIGHT_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_ee_height.params.std="${EE_HEIGHT_REWARD_STD}" \
  "manager_env.rewards.tracking_ee_height.params.body_names=${EE_HEIGHT_BODY_NAMES}" \
  manager_env.rewards.tracking_anchor_pos.weight="${ANCHOR_POS_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_anchor_pos.params.std="${ANCHOR_POS_REWARD_STD}" \
  manager_env.rewards.tracking_anchor_linvel.weight="${ANCHOR_LINVEL_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_anchor_linvel.params.std="${ANCHOR_LINVEL_REWARD_STD}" \
  manager_env.rewards.anchor_path_error_penalty.weight="${ANCHOR_PATH_ERROR_WEIGHT}" \
  manager_env.rewards.anchor_path_error_penalty.params.along_tolerance_m="${ANCHOR_PATH_ALONG_TOLERANCE_M}" \
  manager_env.rewards.anchor_path_error_penalty.params.cross_tolerance_m="${ANCHOR_PATH_CROSS_TOLERANCE_M}" \
  manager_env.rewards.anchor_path_error_penalty.params.along_normalization_m="${ANCHOR_PATH_ALONG_NORMALIZATION_M}" \
  manager_env.rewards.anchor_path_error_penalty.params.cross_normalization_m="${ANCHOR_PATH_CROSS_NORMALIZATION_M}" \
  manager_env.rewards.anchor_path_error_penalty.params.min_path_length_m="${ANCHOR_PATH_MIN_LENGTH_M}" \
  manager_env.rewards.tracking_anchor_pos.params.single_support_lateral_scale="${SINGLE_SUPPORT_ANCHOR_LATERAL_SCALE}" \
  manager_env.rewards.tracking_anchor_pos.params.preparation_future_frame_index="${SINGLE_SUPPORT_TRACKING_PREPARATION_FUTURE_FRAME_INDEX}" \
  manager_env.rewards.tracking_anchor_ori.weight="${ANCHOR_ORI_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_relative_body_pos.weight="${RELATIVE_BODY_POS_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_relative_body_pos.params.single_support_stance_body_scale="${SINGLE_SUPPORT_STANCE_BODY_SCALE}" \
  manager_env.rewards.tracking_relative_body_pos.params.preparation_future_frame_index="${SINGLE_SUPPORT_TRACKING_PREPARATION_FUTURE_FRAME_INDEX}" \
  manager_env.rewards.tracking_vr_5point_local.params.single_support_stance_foot_scale="${SINGLE_SUPPORT_STANCE_FOOT_SCALE}" \
  manager_env.rewards.tracking_vr_5point_local.params.preparation_future_frame_index="${SINGLE_SUPPORT_TRACKING_PREPARATION_FUTURE_FRAME_INDEX}" \
  manager_env.rewards.joint_limit.weight="${JOINT_LIMIT_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_selected_joint_pos.weight="${SELECTED_JOINT_TRACKING_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_selected_joint_pos.params.std="${SELECTED_JOINT_TRACKING_REWARD_STD}" \
  "manager_env.rewards.tracking_selected_joint_pos.params.joint_names=${SELECTED_JOINT_TRACKING_NAMES}" \
  manager_env.rewards.feet_acc.weight="${FEET_ACC_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_foot_contact_phase.weight="${FOOT_CONTACT_PHASE_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_foot_contact_phase.params.force_threshold="${FOOT_CONTACT_FORCE_THRESHOLD}" \
  manager_env.rewards.tracking_foot_contact_phase.params.swing_contact_cost="${FOOT_CONTACT_SWING_CONTACT_COST}" \
  manager_env.rewards.tracking_foot_contact_phase.params.missed_stance_cost="${FOOT_CONTACT_MISSED_STANCE_COST}" \
  manager_env.rewards.tracking_foot_contact_phase.params.continuous_load="${FOOT_CONTACT_CONTINUOUS_LOAD}" \
  manager_env.rewards.tracking_foot_contact_phase.params.continuous_load_mode="${FOOT_CONTACT_CONTINUOUS_LOAD_MODE}" \
  manager_env.rewards.tracking_foot_contact_phase.params.swing_force_normalizer="${FOOT_CONTACT_SWING_FORCE_NORMALIZER}" \
  manager_env.rewards.tracking_foot_contact_phase.params.support_force_fraction_of_weight="${FOOT_CONTACT_SUPPORT_FORCE_FRACTION_OF_WEIGHT}" \
  manager_env.rewards.tracking_foot_contact_phase.params.left_swing_cost_scale="${FOOT_CONTACT_LEFT_SWING_COST_SCALE}" \
  manager_env.rewards.tracking_foot_contact_phase.params.right_swing_cost_scale="${FOOT_CONTACT_RIGHT_SWING_COST_SCALE}" \
  manager_env.rewards.tracking_foot_contact_phase.params.preparation_future_frame_index="${FOOT_CONTACT_PREPARATION_FUTURE_FRAME_INDEX}" \
  manager_env.rewards.tracking_foot_contact_phase.params.preparation_preserve_double_contact="${FOOT_CONTACT_PREPARATION_PRESERVE_DOUBLE_CONTACT}" \
  manager_env.rewards.tracking_reference_swing_foot_height.weight="${SWING_FOOT_HEIGHT_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_reference_swing_foot_height.params.std="${SWING_FOOT_HEIGHT_REWARD_STD}" \
  manager_env.rewards.tracking_single_support_com.weight="${SINGLE_SUPPORT_COM_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_single_support_com.params.normalization_m="${SINGLE_SUPPORT_COM_NORMALIZATION_M}" \
  manager_env.rewards.tracking_single_support_com.params.preparation_future_frame_index="${SINGLE_SUPPORT_COM_PREPARATION_FUTURE_FRAME_INDEX}" \
  manager_env.rewards.tracking_reference_stance_foot_slip.weight="${REFERENCE_STANCE_FOOT_SLIP_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_reference_stance_foot_slip.params.speed_normalization_mps="${REFERENCE_STANCE_FOOT_SLIP_NORMALIZATION_MPS}" \
  manager_env.rewards.tracking_interfoot_relative_pos.weight="${INTERFOOT_RELATIVE_POS_REWARD_WEIGHT}" \
  manager_env.rewards.tracking_interfoot_relative_pos.params.std="${INTERFOOT_RELATIVE_POS_REWARD_STD}" \
  "manager_env.rewards.anti_shake_ang_vel.params.body_names=${ANTI_SHAKE_BODY_NAMES}" \
  manager_env.rewards.is_terminated.weight="${TERMINATION_PENALTY_WEIGHT}" \
  manager_env.rewards.motion_completion_bonus.weight="${MOTION_COMPLETION_BONUS_WEIGHT}" \
  manager_env.rewards.ee_termination_penalty.weight="${EE_TERMINATION_PENALTY_WEIGHT}" \
  manager_env.rewards.foot_termination_penalty.weight="${FOOT_TERMINATION_PENALTY_WEIGHT}" \
  manager_env.rewards.ee_body_pos_risk.weight="${EE_BODY_POS_RISK_WEIGHT}" \
  manager_env.rewards.ee_body_pos_risk.params.onset="${EE_BODY_POS_RISK_ONSET}" \
  manager_env.rewards.ee_body_pos_risk.params.threshold="${EE_BODY_POS_THRESHOLD}" \
  "manager_env.rewards.ee_body_pos_risk.params.body_names=${EE_BODY_NAMES}" \
  manager_env.rewards.foot_body_pos_risk.weight="${FOOT_BODY_POS_RISK_WEIGHT}" \
  manager_env.rewards.foot_body_pos_risk.params.onset="${FOOT_BODY_POS_RISK_ONSET}" \
  manager_env.rewards.foot_body_pos_risk.params.threshold="${FOOT_POS_XYZ_THRESHOLD}" \
  manager_env.rewards.anchor_pos_termination_risk.weight="${ANCHOR_POS_RISK_WEIGHT}" \
  manager_env.rewards.anchor_pos_termination_risk.params.onset="${ANCHOR_POS_RISK_ONSET}" \
  manager_env.rewards.anchor_pos_termination_risk.params.threshold="${ANCHOR_POS_THRESHOLD}" \
  manager_env.rewards.anchor_ori_termination_risk.weight="${ANCHOR_ORI_RISK_WEIGHT}" \
  manager_env.rewards.anchor_ori_termination_risk.params.onset="${ANCHOR_ORI_RISK_ONSET}" \
  manager_env.rewards.anchor_ori_termination_risk.params.threshold="${ANCHOR_ORI_FULL_THRESHOLD}" \
  manager_env/recorders="${RENDER_RECORDERS}" \
  manager_env.config.render_results="${RENDER_RESULTS}" \
  +manager_env.config.render_width="${RENDER_WIDTH}" \
  +manager_env.config.render_height="${RENDER_HEIGHT}" \
  +manager_env.config.render_frame_skip="${RENDER_FRAME_SKIP}" \
  +manager_env.config.max_render_envs="${MAX_RENDER_ENVS}" \
  manager_env.config.experiment_dir="${LOG_ROOT}/${RUN_NAME}" \
  manager_env.config.save_rendering_dir="${LOG_ROOT}/${RUN_NAME}/renderings" \
  "manager_env.config.train_only_events=${TRAIN_ONLY_EVENTS}" \
  '+manager_env.config.train_only_terminations=[]' \
  manager_env.commands.motion.motion_lib_cfg.multi_thread=False \
  manager_env.commands.motion.motion_lib_cfg.motion_file="${MOTION_FILE}" \
  manager_env.commands.motion.motion_lib_cfg.adaptive_sampling.enable="${ADAPTIVE_SAMPLING_ENABLED}" \
  manager_env.commands.motion.motion_lib_cfg.adaptive_sampling.bin_size="${ADAPTIVE_SAMPLING_BIN_SIZE}" \
  manager_env.commands.motion.motion_lib_cfg.adaptive_sampling.uniform_sampling_rate="${ADAPTIVE_SAMPLING_UNIFORM_RATE}" \
  manager_env.commands.motion.motion_lib_cfg.adaptive_sampling.pre_failure_sample_window="${ADAPTIVE_SAMPLING_PRE_FAILURE_WINDOW}" \
  +manager_env.commands.motion.motion_lib_cfg.adaptive_sampling.max_prob_per_bin="${ADAPTIVE_SAMPLING_MAX_PROB_PER_BIN}" \
  +manager_env.commands.motion.motion_lib_cfg.adaptive_sampling.max_prob_per_motion="${ADAPTIVE_SAMPLING_MAX_PROB_PER_MOTION}" \
  +manager_env.commands.motion.motion_lib_cfg.foot_contact_label_mode="${FOOT_CONTACT_LABEL_MODE}" \
  +manager_env.commands.motion.motion_lib_cfg.foot_contact_ground_percentile="${FOOT_CONTACT_GROUND_PERCENTILE}" \
  +manager_env.commands.motion.motion_lib_cfg.foot_contact_height_margin_m="${FOOT_CONTACT_HEIGHT_MARGIN_M}" \
  +manager_env.commands.motion.motion_lib_cfg.foot_contact_vertical_speed_max_mps="${FOOT_CONTACT_VERTICAL_SPEED_MAX_MPS}" \
  +manager_env.commands.motion.motion_lib_cfg.foot_contact_max_ground_band_height_m="${FOOT_CONTACT_MAX_GROUND_BAND_M}" \
  +manager_env.commands.motion.use_paired_motions="${USE_PAIRED_MOTIONS}" \
  +manager_env.commands.motion.start_from_first_frame="${START_FROM_FIRST_FRAME}" \
  +manager_env.commands.motion.paired_start_mode_pattern="${PAIRED_START_MODE_PATTERN}" \
  +manager_env.commands.motion.preserve_auto_reset_frame_zero="${PRESERVE_AUTO_RESET_FRAME_ZERO}" \
  +manager_env.commands.motion.contact_phase_sync_enabled="${CONTACT_PHASE_SYNC_ENABLED}" \
  +manager_env.commands.motion.contact_phase_sync_lower_body_only="${CONTACT_PHASE_SYNC_LOWER_BODY_ONLY}" \
  +manager_env.commands.motion.contact_phase_sync_lower_body_blend="${CONTACT_PHASE_SYNC_LOWER_BODY_BLEND}" \
  "+manager_env.commands.motion.contact_phase_sync_lower_body_pair_blends=${CONTACT_PHASE_SYNC_LOWER_BODY_PAIR_BLENDS}" \
  +manager_env.commands.motion.contact_phase_sync_lead_steps="${CONTACT_PHASE_SYNC_LEAD_STEPS}" \
  +manager_env.commands.motion.contact_phase_sync_lag_steps="${CONTACT_PHASE_SYNC_LAG_STEPS}" \
  +manager_env.commands.motion.contact_phase_sync_max_advance_per_step="${CONTACT_PHASE_SYNC_MAX_ADVANCE_PER_STEP}" \
  +manager_env.commands.motion.contact_phase_sync_force_threshold="${CONTACT_PHASE_SYNC_FORCE_THRESHOLD}" \
  +manager_env.commands.motion.contact_load_gate_enabled="${CONTACT_LOAD_GATE_ENABLED}" \
  +manager_env.commands.motion.contact_load_gate_preview_steps="${CONTACT_LOAD_GATE_PREVIEW_STEPS}" \
  +manager_env.commands.motion.contact_load_gate_max_hold_steps="${CONTACT_LOAD_GATE_MAX_HOLD_STEPS}" \
  +manager_env.commands.motion.contact_load_gate_min_stance_load_share="${CONTACT_LOAD_GATE_MIN_STANCE_SHARE}" \
  +manager_env.commands.motion.contact_load_gate_min_total_load_n="${CONTACT_LOAD_GATE_MIN_TOTAL_LOAD_N}" \
  +manager_env.commands.motion.lower_body_reference_delay_steps="${LOWER_BODY_REFERENCE_DELAY_STEPS}" \
  manager_env.commands.motion.freeze_frame_aug="${FREEZE_FRAME_AUG}" \
  '+manager_env.commands.motion.motion_lib_cfg.randomize_heading=False' \
  '+manager_env.commands.motion.motion_lib_cfg.randomize_wrist_poses=False' \
  '+manager_env.commands.motion.motion_lib_cfg.freeze_frame_aug=False' \
  "+manager_env.commands.motion.motion_lib_cfg.max_unique_motions=${MOTIONS}" \
  "+manager_env.commands.motion.motion_lib_cfg.override_num_motions_to_load=${MOTIONS}" \
  manager_env.commands.motion.anchor_body=base_link \
  'manager_env.commands.motion.vr_3point_body=[left_wrist_roll_link,right_wrist_roll_link,torso_link]' \
  "manager_env.commands.motion.vr_3point_body_offset=${VR_3POINT_OFFSETS}" \
  "manager_env.commands.motion.reward_point_body=${REWARD_POINT_BODY_NAMES}" \
  "manager_env.commands.motion.reward_point_body_offset=${REWARD_POINT_BODY_OFFSETS}" \
  "manager_env.commands.motion.body_names=${TRACKED_BODY_NAMES}" \
  algo.config.num_steps_per_env="${STEPS_PER_ENV}" \
  algo.trl.learning_rate="${ACTOR_LEARNING_RATE}" \
  algo.config.actor_learning_rate="${ACTOR_LEARNING_RATE}" \
  algo.config.critic_learning_rate="${CRITIC_LEARNING_RATE}" \
  +algo.config.ppo_loss_coef="${PPO_LOSS_COEF}" \
  algo.config.adaptive_lr_min="${ADAPTIVE_LR_MIN}" \
  algo.config.adaptive_lr_max="${ADAPTIVE_LR_MAX}" \
  +algo.config.adaptive_kl_floor="${ADAPTIVE_KL_FLOOR}" \
  +algo.config.clamp_noise_std="${CLAMP_NOISE_STD}" \
  +algo.config.max_noise_std="${MAX_NOISE_STD}" \
  +algo.config.deterministic_rollout="${DETERMINISTIC_ROLLOUT}" \
  +algo.config.train_with_evaluating_env="${TRAIN_WITH_EVALUATING_ENV}" \
  +algo.config.paired_action_router.enabled="${PAIRED_ACTION_ROUTER_ENABLED}" \
  +algo.config.paired_action_router.mode="${PAIRED_ACTION_ROUTER_MODE}" \
  +algo.config.paired_action_router.source_env_index="${PAIRED_ACTION_ROUTER_SOURCE_ENV_INDEX}" \
  +algo.config.paired_action_router.target_env_index="${PAIRED_ACTION_ROUTER_TARGET_ENV_INDEX}" \
  +algo.config.paired_action_router.mirror_blend="${PAIRED_ACTION_ROUTER_MIRROR_BLEND}" \
  "+algo.config.paired_action_router.lower_body_action_name_tokens=${PAIRED_ACTION_ROUTER_LOWER_BODY_TOKENS}" \
  +algo.config.x2_semantic_counterfactual.enabled="${X2_SEMANTIC_COUNTERFACTUAL_ENABLED}" \
  +algo.config.x2_semantic_counterfactual.output_path="${X2_SEMANTIC_COUNTERFACTUAL_OUTPUT_PATH}" \
  "+algo.config.x2_semantic_counterfactual.modes=${X2_SEMANTIC_COUNTERFACTUAL_MODES}" \
  +algo.config.x2_semantic_counterfactual.max_steps="${X2_SEMANTIC_COUNTERFACTUAL_MAX_STEPS}" \
  +algo.config.policy_replay_match_rollout="${POLICY_REPLAY_MATCH_ROLLOUT}" \
  +algo.config.critic_only_bypass_actor_replay="${CRITIC_ONLY_BYPASS_ACTOR_REPLAY}" \
  +algo.config.actor_feature_delta_replay="${ACTOR_FEATURE_DELTA_REPLAY}" \
  +algo.config.actor_decoder_delta_replay="${ACTOR_DECODER_DELTA_REPLAY}" \
  +algo.config.actuator_context_residual_gate.enabled="${ACTUATOR_CONTEXT_RESIDUAL_GATE_ENABLED}" \
  +algo.config.actuator_context_residual_gate.ideal_tolerance="${ACTUATOR_CONTEXT_RESIDUAL_GATE_TOLERANCE}" \
  +algo.config.use_separate_actor_critic_lr="${SEPARATE_ACTOR_CRITIC_LR}" \
  +algo.config.preserve_adaptive_optimizer_lr="${PRESERVE_ADAPTIVE_OPTIMIZER_LR}" \
  +algo.config.training_diagnostics.enabled="${TRAINING_DIAGNOSTICS_ENABLED}" \
  +algo.config.training_diagnostics.output_path="${TRAINING_DIAGNOSTICS_PATH}" \
  +algo.config.critic_holdout_export.enabled="${CRITIC_HOLDOUT_EXPORT_ENABLED}" \
  +algo.config.critic_holdout_export.output_path="${CRITIC_HOLDOUT_EXPORT_PATH}" \
  +algo.config.gradient_geometry.enabled="${GRADIENT_GEOMETRY_ENABLED}" \
  +algo.config.gradient_geometry.motion_groups_path="${GRADIENT_GEOMETRY_GROUPS_PATH}" \
  +algo.config.gradient_geometry.output_path="${GRADIENT_GEOMETRY_OUTPUT_PATH}" \
  +algo.config.gradient_geometry.reset_env_each_iteration="${GRADIENT_GEOMETRY_RESET_ENV_EACH_ITERATION}" \
  +algo.config.oracle_action_aux.enabled="${ORACLE_ACTION_AUX_ENABLED}" \
  +algo.config.oracle_action_aux.coef="${ORACLE_ACTION_AUX_COEF}" \
  +algo.config.oracle_action_aux.lookahead_steps="${ORACLE_ACTION_AUX_LOOKAHEAD_STEPS}" \
  +algo.config.oracle_action_aux.target_source="${ORACLE_ACTION_AUX_TARGET_SOURCE}" \
  +algo.config.oracle_action_aux.max_abs_action="${ORACLE_ACTION_AUX_MAX_ABS_ACTION}" \
  "+algo.config.oracle_action_aux.included_action_name_tokens=${ORACLE_ACTION_AUX_TOKENS}" \
  +algo.config.oracle_action_aux.gradient_diagnostics="${ORACLE_ACTION_AUX_GRAD_DIAGNOSTICS}" \
  +algo.config.oracle_action_aux.mode="${ORACLE_ACTION_AUX_MODE}" \
  +algo.config.oracle_action_aux.projected_delta_limit="${ORACLE_ACTION_AUX_PROJECTED_DELTA_LIMIT}" \
  +algo.config.oracle_action_aux.transition_multiplier="${ORACLE_ACTION_AUX_TRANSITION_MULTIPLIER}" \
  +algo.config.balance_oracle_probe.enabled="${BALANCE_ORACLE_PROBE_ENABLED}" \
  +algo.config.balance_oracle_probe.preview_frame_index="${BALANCE_ORACLE_PREVIEW_FRAME_INDEX}" \
  +algo.config.balance_oracle_probe.com_gain="${BALANCE_ORACLE_COM_GAIN}" \
  +algo.config.balance_oracle_probe.com_velocity_horizon_s="${BALANCE_ORACLE_COM_VELOCITY_HORIZON_S}" \
  +algo.config.balance_oracle_probe.damping="${BALANCE_ORACLE_DAMPING}" \
  +algo.config.balance_oracle_probe.max_abs_joint_delta_rad="${BALANCE_ORACLE_MAX_ABS_JOINT_DELTA_RAD}" \
  +algo.config.balance_oracle_probe.preparation_swing_load_share="${BALANCE_ORACLE_PREPARATION_SWING_LOAD_SHARE}" \
  +algo.config.balance_oracle_probe.single_support_swing_load_share="${BALANCE_ORACLE_SINGLE_SUPPORT_SWING_LOAD_SHARE}" \
  +algo.config.balance_oracle_probe.preparation_only="${BALANCE_ORACLE_PREPARATION_ONLY}" \
  +algo.config.balance_oracle_probe.solver_mode="${BALANCE_ORACLE_SOLVER_MODE}" \
  +algo.config.balance_oracle_probe.virtual_force_natural_frequency_hz="${BALANCE_ORACLE_VIRTUAL_FORCE_NATURAL_FREQUENCY_HZ}" \
  +algo.config.balance_oracle_probe.virtual_force_damping_ratio="${BALANCE_ORACLE_VIRTUAL_FORCE_DAMPING_RATIO}" \
  "+algo.config.balance_oracle_probe.included_action_name_tokens=${BALANCE_ORACLE_ACTION_TOKENS}" \
  +algo.config.decoupled_locomotion_probe.enabled="${DECOUPLED_LOCOMOTION_PROBE_ENABLED}" \
  +algo.config.decoupled_locomotion_probe.balance_model_path="${DECOUPLED_LOCOMOTION_BALANCE_MODEL_PATH}" \
  +algo.config.decoupled_locomotion_probe.walk_model_path="${DECOUPLED_LOCOMOTION_WALK_MODEL_PATH}" \
  +algo.config.decoupled_locomotion_probe.mode="${DECOUPLED_LOCOMOTION_MODE}" \
  +algo.config.decoupled_locomotion_probe.residual_scale_rad="${DECOUPLED_LOCOMOTION_RESIDUAL_SCALE_RAD}" \
  +algo.config.decoupled_locomotion_probe.height_command_m="${DECOUPLED_LOCOMOTION_HEIGHT_COMMAND_M}" \
  +algo.config.decoupled_locomotion_probe.reference_velocity_gain="${DECOUPLED_LOCOMOTION_REFERENCE_VELOCITY_GAIN}" \
  +algo.config.decoupled_locomotion_probe.max_command_x_mps="${DECOUPLED_LOCOMOTION_MAX_COMMAND_X_MPS}" \
  +algo.config.decoupled_locomotion_probe.max_command_y_mps="${DECOUPLED_LOCOMOTION_MAX_COMMAND_Y_MPS}" \
  +algo.config.decoupled_locomotion_probe.max_command_yaw_rps="${DECOUPLED_LOCOMOTION_MAX_COMMAND_YAW_RPS}" \
  +algo.config.decoupled_locomotion_probe.history_length="${DECOUPLED_LOCOMOTION_HISTORY_LENGTH}" \
  +algo.config.decoupled_locomotion_probe.auto_walk_threshold="${DECOUPLED_LOCOMOTION_AUTO_WALK_THRESHOLD}" \
  +algo.config.twist_teacher_probe.enabled="${TWIST_TEACHER_PROBE_ENABLED}" \
  +algo.config.twist_teacher_probe.model_path="${TWIST_TEACHER_MODEL_PATH}" \
  +algo.config.twist_teacher_probe.expected_sha256="${TWIST_TEACHER_EXPECTED_SHA256}" \
  +algo.config.twist_teacher_probe.ownership="${TWIST_TEACHER_OWNERSHIP}" \
  +algo.config.twist_teacher_probe.raw_action_clip="${TWIST_TEACHER_RAW_ACTION_CLIP}" \
  +algo.config.twist_teacher_probe.action_scale_rad="${TWIST_TEACHER_ACTION_SCALE_RAD}" \
  +algo.config.twist_teacher_probe.reference_lookahead_steps="${TWIST_TEACHER_REFERENCE_LOOKAHEAD_STEPS}" \
  +algo.config.twist_teacher_probe.clamp_to_joint_limits="${TWIST_TEACHER_CLAMP_TO_JOINT_LIMITS}" \
  +algo.config.twist_teacher_probe.mode="${TWIST_TEACHER_MODE}" \
  +algo.config.twist_teacher_probe.residual_max_abs_delta_rad="${TWIST_TEACHER_RESIDUAL_MAX_ABS_DELTA_RAD}" \
  +algo.config.twist_teacher_probe.residual_preparation_only="${TWIST_TEACHER_RESIDUAL_PREPARATION_ONLY}" \
  +algo.config.twist_teacher_probe.residual_preview_frame_index="${TWIST_TEACHER_RESIDUAL_PREVIEW_FRAME_INDEX}" \
  +algo.config.twist_teacher_probe.residual_min_motion_step="${TWIST_TEACHER_RESIDUAL_MIN_MOTION_STEP}" \
  "+algo.config.twist_teacher_probe.residual_direction_factors=${TWIST_TEACHER_RESIDUAL_DIRECTION_FACTORS}" \
  +algo.config.twist_teacher_probe.residual_action_source_copy_index="${TWIST_TEACHER_RESIDUAL_ACTION_SOURCE_COPY_INDEX}" \
  +algo.config.twist_teacher_probe.residual_direction_factor="${TWIST_TEACHER_RESIDUAL_DIRECTION_FACTOR}" \
  +algo.config.twist_teacher_probe.residual_basis="${TWIST_TEACHER_RESIDUAL_BASIS}" \
  +algo.config.twist_teacher_probe.residual_hold_steps="${TWIST_TEACHER_RESIDUAL_HOLD_STEPS}" \
  +algo.config.twist_teacher_probe.residual_sequence_first_basis="${TWIST_TEACHER_SEQUENCE_FIRST_BASIS}" \
  +algo.config.twist_teacher_probe.residual_sequence_second_basis="${TWIST_TEACHER_SEQUENCE_SECOND_BASIS}" \
  +algo.config.twist_teacher_probe.residual_sequence_first_steps="${TWIST_TEACHER_SEQUENCE_FIRST_STEPS}" \
  +algo.config.twist_teacher_probe.residual_sequence_second_steps="${TWIST_TEACHER_SEQUENCE_SECOND_STEPS}" \
  +algo.config.twist_teacher_probe.residual_sequence_first_delta_rad="${TWIST_TEACHER_SEQUENCE_FIRST_DELTA_RAD}" \
  +algo.config.twist_teacher_probe.residual_sequence_second_delta_rad="${TWIST_TEACHER_SEQUENCE_SECOND_DELTA_RAD}" \
  +algo.config.twist_teacher_probe.residual_sequence_feedback_mode="${TWIST_TEACHER_SEQUENCE_FEEDBACK_MODE}" \
  +algo.config.twist_teacher_probe.residual_sequence_feedback_position_normalizer_m="${TWIST_TEACHER_SEQUENCE_FEEDBACK_POSITION_NORMALIZER_M}" \
  +algo.config.twist_teacher_probe.residual_sequence_feedback_min_scale="${TWIST_TEACHER_SEQUENCE_FEEDBACK_MIN_SCALE}" \
  +algo.config.twist_teacher_probe.residual_sequence_feedback_max_scale="${TWIST_TEACHER_SEQUENCE_FEEDBACK_MAX_SCALE}" \
  +algo.config.twist_teacher_probe.residual_spline_horizon_steps="${TWIST_TEACHER_SPLINE_HORIZON_STEPS}" \
  "+algo.config.twist_teacher_probe.residual_spline_hip_roll_knots_rad=${TWIST_TEACHER_SPLINE_HIP_ROLL_KNOTS_RAD}" \
  "+algo.config.twist_teacher_probe.residual_spline_waist_roll_knots_rad=${TWIST_TEACHER_SPLINE_WAIST_ROLL_KNOTS_RAD}" \
  "+algo.config.twist_teacher_probe.residual_spline_stance_hip_pitch_forward_knots_rad=${TWIST_TEACHER_SPLINE_STANCE_HIP_PITCH_FORWARD_KNOTS_RAD}" \
  "+algo.config.twist_teacher_probe.residual_spline_swing_knee_knots_rad=${TWIST_TEACHER_SPLINE_SWING_KNEE_KNOTS_RAD}" \
  "+algo.config.twist_teacher_probe.residual_spline_swing_ankle_pitch_knots_rad=${TWIST_TEACHER_SPLINE_SWING_ANKLE_PITCH_KNOTS_RAD}" \
  +algo.config.constraint_gradient_geometry.enabled="${CONSTRAINT_GRADIENT_GEOMETRY_ENABLED}" \
  +algo.config.constraint_gradient_geometry.output_path="${CONSTRAINT_GRADIENT_GEOMETRY_OUTPUT_PATH}" \
  +algo.config.constraint_gradient_geometry.tolerances.root_pos="${CONSTRAINT_ROOT_POS_TOLERANCE}" \
  +algo.config.constraint_gradient_geometry.tolerances.root_ori="${CONSTRAINT_ROOT_ORI_TOLERANCE}" \
  +algo.config.constraint_gradient_geometry.tolerances.left_wrist="${CONSTRAINT_LEFT_WRIST_TOLERANCE}" \
  +algo.config.constraint_gradient_geometry.tolerances.right_wrist="${CONSTRAINT_RIGHT_WRIST_TOLERANCE}" \
  +algo.config.constraint_gradient_geometry.tolerances.foot="${CONSTRAINT_FOOT_TOLERANCE}" \
  +algo.config.constraint_gradient_geometry.tolerances.waist="${CONSTRAINT_WAIST_TOLERANCE}" \
  +algo.config.constraint_optimization.enabled="${CONSTRAINT_OPTIMIZATION_ENABLED}" \
  +algo.config.constraint_optimization.history_path="${CONSTRAINT_OPTIMIZATION_HISTORY_PATH}" \
  +algo.config.constraint_optimization.dual_learning_rate="${CONSTRAINT_DUAL_LEARNING_RATE}" \
  +algo.config.constraint_optimization.initial_multiplier="${CONSTRAINT_INITIAL_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multiplier="${CONSTRAINT_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multipliers.root_pos="${CONSTRAINT_ROOT_POS_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multipliers.root_ori="${CONSTRAINT_ROOT_ORI_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multipliers.left_wrist="${CONSTRAINT_LEFT_WRIST_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multipliers.right_wrist="${CONSTRAINT_RIGHT_WRIST_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multipliers.foot="${CONSTRAINT_FOOT_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.max_multipliers.waist="${CONSTRAINT_WAIST_MAX_MULTIPLIER}" \
  +algo.config.constraint_optimization.dual_update_mode="${CONSTRAINT_DUAL_UPDATE_MODE}" \
  +algo.config.constraint_optimization.risk_mode="${CONSTRAINT_RISK_MODE}" \
  +algo.config.constraint_optimization.risk_quantile="${CONSTRAINT_RISK_QUANTILE}" \
  +algo.config.constraint_optimization.surrogate_tail_quantile="${CONSTRAINT_SURROGATE_TAIL_QUANTILE}" \
  +algo.config.constraint_optimization.motion_balanced="${CONSTRAINT_MOTION_BALANCED}" \
  +algo.config.constraint_optimization.motion_risk_reduction="${CONSTRAINT_MOTION_RISK_REDUCTION}" \
  +algo.config.constraint_optimization.motion_risk_top_fraction="${CONSTRAINT_MOTION_RISK_TOP_FRACTION}" \
  +algo.config.constraint_optimization.motion_equal_surrogate="${CONSTRAINT_MOTION_EQUAL_SURROGATE}" \
  +algo.config.constraint_optimization.initial_lora_anchor_coef="${CONSTRAINT_LORA_ANCHOR_COEF}" \
  +algo.config.constraint_optimization.initial_lora_anchor_tolerance="${CONSTRAINT_LORA_ANCHOR_TOLERANCE}" \
  +algo.config.constraint_optimization.tolerances.root_pos="${CONSTRAINT_ROOT_POS_TOLERANCE}" \
  +algo.config.constraint_optimization.tolerances.root_ori="${CONSTRAINT_ROOT_ORI_TOLERANCE}" \
  +algo.config.constraint_optimization.tolerances.left_wrist="${CONSTRAINT_LEFT_WRIST_TOLERANCE}" \
  +algo.config.constraint_optimization.tolerances.right_wrist="${CONSTRAINT_RIGHT_WRIST_TOLERANCE}" \
  +algo.config.constraint_optimization.tolerances.foot="${CONSTRAINT_FOOT_TOLERANCE}" \
  +algo.config.constraint_optimization.tolerances.waist="${CONSTRAINT_WAIST_TOLERANCE}" \
  +algo.config.constraint_optimization.budgets.root_pos="${CONSTRAINT_ROOT_POS_BUDGET}" \
  +algo.config.constraint_optimization.budgets.root_ori="${CONSTRAINT_ROOT_ORI_BUDGET}" \
  +algo.config.constraint_optimization.budgets.left_wrist="${CONSTRAINT_LEFT_WRIST_BUDGET}" \
  +algo.config.constraint_optimization.budgets.right_wrist="${CONSTRAINT_RIGHT_WRIST_BUDGET}" \
  +algo.config.constraint_optimization.budgets.foot="${CONSTRAINT_FOOT_BUDGET}" \
  +algo.config.constraint_optimization.budgets.waist="${CONSTRAINT_WAIST_BUDGET}" \
  algo.config.num_learning_epochs="${PPO_EPOCHS}" \
  algo.config.num_mini_batches="${NUM_MINI_BATCHES}" \
  algo.trl.gradient_accumulation_steps="${GRADIENT_ACCUMULATION_STEPS}" \
  +algo.config.ppo_shuffle_enabled="${PPO_SHUFFLE_ENABLED}" \
  algo.config.ppo_shuffle_every_epoch="${PPO_SHUFFLE_EVERY_EPOCH}" \
  algo.config.num_learning_iterations="${ITERS}" \
  algo.trl.num_total_batches="${ITERS}" \
  algo.trl.total_episodes="${TOTAL_EPISODES}" \
  algo.trl.save_strategy=no \
  callbacks.model_save.save_frequency="${SAVE_FREQUENCY}" \
  "+callbacks.model_save.save_last_frequency=${SAVE_LAST_FREQUENCY}" \
  algo.trl.report_to=none \
  algo.trl.disable_tqdm=True \
  +algo.config.compute_aux_loss=False \
  +algo.config.x2_wrist_diagnostics.enabled="${WRIST_DIAGNOSTICS}" \
  +algo.config.x2_wrist_diagnostics.output_path="${WRIST_TRACE}" \
  +algo.config.any2any_lora.enabled=True \
  +algo.config.any2any_lora.rank=8 \
  +algo.config.any2any_lora.alpha=16 \
  +algo.config.any2any_lora.dropout=0.0 \
  +algo.config.any2any_lora.train_actor="${TRAIN_ACTOR_LORA}" \
  +algo.config.any2any_lora.train_critic="${TRAIN_CRITIC_LORA}" \
  +algo.config.any2any_lora.semantic_copy_mismatched=True \
  +algo.config.any2any_lora.semantic_copy_strict="${SEMANTIC_COPY_STRICT}" \
  +algo.config.any2any_lora.preserve_checkpoint_residual="${PRESERVE_LORA_CHECKPOINT}" \
  +algo.config.any2any_lora.stack_checkpoint_residual="${STACK_LORA_CHECKPOINT_RESIDUAL}" \
  +algo.config.any2any_lora.preserve_appended_critic_features="${PRESERVE_APPENDED_CRITIC_FEATURES}" \
  +algo.config.any2any_lora.semantic_neutral_init_unmapped="${SEMANTIC_NEUTRAL_INIT_UNMAPPED}" \
  "+algo.config.any2any_lora.actor_lora_prefixes=${ACTOR_LORA_PREFIXES}" \
  +algo.config.any2any_lora.actor_input_mask.enabled="${ACTOR_INPUT_MASK_ENABLED}" \
  "+algo.config.any2any_lora.actor_input_mask.layer_names=${ACTOR_INPUT_MASK_LAYERS}" \
  +algo.config.any2any_lora.actor_input_mask.decoder_name="${ACTOR_INPUT_MASK_DECODER}" \
  "+algo.config.any2any_lora.actor_input_mask.include_features=${ACTOR_INPUT_MASK_FEATURES}" \
  +algo.config.any2any_lora.actor_output_mask.enabled="${ACTOR_OUTPUT_MASK_ENABLED}" \
  "+algo.config.any2any_lora.actor_output_mask.layer_names=${ACTOR_OUTPUT_MASK_LAYERS}" \
  "+algo.config.any2any_lora.actor_output_mask.include_action_name_tokens=${ACTOR_OUTPUT_MASK_TOKENS}" \
  +algo.config.any2any_lora.actor_output_mask.unselected_action_scale="${ACTOR_OUTPUT_UNSELECTED_SCALE}" \
  "+algo.config.any2any_lora.actor_output_mask.auxiliary_action_name_tokens=${ACTOR_OUTPUT_AUX_TOKENS}" \
  +algo.config.any2any_lora.actor_output_mask.auxiliary_action_scale="${ACTOR_OUTPUT_AUX_SCALE}" \
  '+algo.config.any2any_lora.actor_output_mask.excluded_action_names=[head_yaw_joint,head_pitch_joint]' \
  +algo.config.any2any_lora.actor_decoder_action_delta_projection.enabled="${ACTOR_DECODER_ACTION_PROJECTION_ENABLED}" \
  +algo.config.any2any_lora.actor_decoder_action_delta_projection.decoder_name="${ACTOR_DECODER_ACTION_PROJECTION_DECODER}" \
  +algo.config.any2any_lora.response_aware.enabled="${RESPONSE_AWARE_LORA_ENABLED}" \
  '+algo.config.any2any_lora.response_aware.decoder_name=g1_dyn' \
  "+algo.config.any2any_lora.response_aware.layer_names=${RESPONSE_AWARE_LORA_LAYERS}" \
  '+algo.config.any2any_lora.response_aware.response_feature_name=x2_actuator_tracking_state' \
  '+algo.config.any2any_lora.response_aware.contact_feature_name=command_multi_future_foot_contacts' \
  +algo.config.any2any_lora.response_aware.input_scale="${RESPONSE_AWARE_INPUT_SCALE}" \
  +algo.config.any2any_lora.response_aware.hidden_dim="${RESPONSE_AWARE_HIDDEN_DIM}" \
  +algo.config.any2any_lora.response_aware.max_condition="${RESPONSE_AWARE_MAX_CONDITION}" \
  +algo.config.any2any_lora.response_aware.history_length="${RESPONSE_AWARE_HISTORY_LENGTH}" \
  +algo.config.any2any_lora.response_aware.joint_count="${RESPONSE_AWARE_JOINT_COUNT}" \
  +algo.config.any2any_lora.response_aware.target_position_scale="${RESPONSE_AWARE_TARGET_POSITION_SCALE}" \
  +algo.config.any2any_lora.response_aware.joint_position_scale="${RESPONSE_AWARE_JOINT_POSITION_SCALE}" \
  +algo.config.any2any_lora.response_aware.joint_velocity_scale="${RESPONSE_AWARE_JOINT_VELOCITY_SCALE}" \
  +algo.config.any2any_lora.response_aware.tracking_error_scale="${RESPONSE_AWARE_TRACKING_ERROR_SCALE}" \
  "+algo.config.any2any_lora.response_aware.joint_include_tokens=${RESPONSE_AWARE_JOINT_INCLUDE_TOKENS}" \
  "+algo.config.any2any_lora.response_aware.output_action_name_tokens=${RESPONSE_AWARE_OUTPUT_ACTION_TOKENS}" \
  +algo.config.any2any_lora.response_aware.contact_gate_by_tracking_error="${RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR}" \
  +algo.config.any2any_lora.response_aware.tracking_error_activity_scale="${RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE}" \
  +algo.config.any2any_lora.response_aware.train_response_only="${RESPONSE_AWARE_TRAIN_RESPONSE_ONLY}" \
  +algo.config.any2any_lora.pretrain_export_path="${PRETRAIN_EXPORT_PATH}" \
  '+algo.config.any2any_lora.critic_lora_prefixes=[critic_module]' \
  "+algo.config.any2any_lora.train_boundary_keys=${TRAIN_BOUNDARY_KEYS}" \
  +algo.config.source_policy_retention.enabled="${SOURCE_RETENTION_ENABLED}" \
  +algo.config.source_policy_retention.action_mean_coef="${SOURCE_RETENTION_ACTION_COEF}" \
  +algo.config.source_policy_retention.lora_weight_coef="${SOURCE_RETENTION_LORA_COEF}" \
  +algo.config.source_policy_retention.action_mean_tolerance="${SOURCE_RETENTION_ACTION_TOLERANCE}" \
  +algo.config.source_policy_retention.lora_weight_tolerance="${SOURCE_RETENTION_LORA_TOLERANCE}" \
  +algo.config.source_policy_retention.fixed_replay.enabled="${SOURCE_RETENTION_FIXED_REPLAY_ENABLED}" \
  +algo.config.source_policy_retention.fixed_replay.action_mean_coef="${SOURCE_RETENTION_FIXED_REPLAY_COEF}" \
  +algo.config.source_policy_retention.fixed_replay.action_mean_tolerance="${SOURCE_RETENTION_FIXED_REPLAY_TOLERANCE}" \
  +algo.config.source_policy_retention.fixed_replay.phase_balanced="${SOURCE_RETENTION_FIXED_REPLAY_PHASE_BALANCED}" \
  +algo.config.source_policy_retention.fixed_replay.transition_multiplier="${SOURCE_RETENTION_FIXED_REPLAY_TRANSITION_MULTIPLIER}" \
  +algo.config.source_policy_retention.reference_mode="${SOURCE_RETENTION_REFERENCE_MODE}" \
  +algo.config.source_policy_retention.lower_body_multiplier="${SOURCE_RETENTION_LOWER_BODY_MULT}" \
  "+algo.config.source_policy_retention.included_action_name_tokens=${SOURCE_RETENTION_INCLUDED_TOKENS}" \
  +algo.config.source_policy_retention.ideal_actuator_context_only="${SOURCE_RETENTION_IDEAL_CONTEXT_ONLY}" \
  +algo.config.source_policy_retention.ideal_actuator_context_tolerance="${SOURCE_RETENTION_IDEAL_CONTEXT_TOLERANCE}" \
  +algo.config.source_policy_retention.gate_aware.enabled="${GATE_AWARE_RETENTION_ENABLED}" \
  +algo.config.source_policy_retention.gate_aware.root_error_metric="${GATE_AWARE_ROOT_METRIC}" \
  +algo.config.source_policy_retention.gate_aware.root_error_onset="${GATE_AWARE_ROOT_ONSET}" \
  +algo.config.source_policy_retention.gate_aware.root_error_threshold="${GATE_AWARE_ROOT_THRESHOLD}" \
  +algo.config.source_policy_retention.gate_aware.max_multiplier="${GATE_AWARE_MAX_MULTIPLIER}" \
  +algo.config.source_policy_retention.gate_aware.exponent=2.0 \
  +algo.config.source_policy_retention.gate_aware.ee_height_enabled="${GATE_AWARE_EE_RETENTION_ENABLED}" \
  +algo.config.source_policy_retention.gate_aware.ee_height_onset="${GATE_AWARE_EE_ONSET}" \
  +algo.config.source_policy_retention.gate_aware.ee_height_threshold="${GATE_AWARE_EE_THRESHOLD}" \
  +algo.config.source_policy_retention.gate_aware.ee_height_max_multiplier="${GATE_AWARE_EE_MAX_MULTIPLIER}" \
  +algo.config.source_policy_retention.gate_aware.ee_height_exponent="${GATE_AWARE_EE_EXPONENT}" \
  "+algo.config.source_policy_retention.gate_aware.ee_height_body_names=${GATE_AWARE_EE_BODY_NAMES}" \
  +algo.config.source_policy_retention.gate_aware.foot_pos_enabled="${GATE_AWARE_FOOT_RETENTION_ENABLED}" \
  +algo.config.source_policy_retention.gate_aware.foot_pos_onset="${GATE_AWARE_FOOT_ONSET}" \
  +algo.config.source_policy_retention.gate_aware.foot_pos_threshold="${GATE_AWARE_FOOT_THRESHOLD}" \
  +algo.config.source_policy_retention.gate_aware.foot_pos_max_multiplier="${GATE_AWARE_FOOT_MAX_MULTIPLIER}" \
  +algo.config.source_policy_retention.gate_aware.foot_pos_exponent="${GATE_AWARE_FOOT_EXPONENT}" \
  "+algo.config.source_policy_retention.gate_aware.foot_pos_body_names=${GATE_AWARE_FOOT_BODY_NAMES}" \
  +algo.config.source_policy_retention.gate_aware.risk_combine_mode="${GATE_AWARE_RISK_COMBINE_MODE}" \
  '+algo.config.source_policy_retention.excluded_action_names=[head_yaw_joint,head_pitch_joint]' \
  +algo.config.runtime_residual_blend.enabled="${RUNTIME_RESIDUAL_BLEND_ENABLED}" \
  +algo.config.runtime_residual_blend.root_error_enabled="${RUNTIME_BLEND_ROOT_ENABLED}" \
  +algo.config.runtime_residual_blend.root_error_onset="${RUNTIME_BLEND_ROOT_ONSET}" \
  +algo.config.runtime_residual_blend.root_error_threshold="${RUNTIME_BLEND_ROOT_THRESHOLD}" \
  +algo.config.runtime_residual_blend.ee_height_enabled="${RUNTIME_BLEND_EE_ENABLED}" \
  +algo.config.runtime_residual_blend.ee_height_onset="${RUNTIME_BLEND_EE_ONSET}" \
  +algo.config.runtime_residual_blend.ee_height_threshold="${RUNTIME_BLEND_EE_THRESHOLD}" \
  "+algo.config.runtime_residual_blend.ee_height_body_names=${RUNTIME_BLEND_EE_BODY_NAMES}" \
  +algo.config.runtime_residual_blend.ee_height_side_specific="${RUNTIME_BLEND_EE_SIDE_SPECIFIC}" \
  "+algo.config.runtime_residual_blend.ee_height_action_name_tokens=${RUNTIME_BLEND_EE_ACTION_TOKENS}" \
  +algo.config.runtime_residual_blend.foot_pos_enabled="${RUNTIME_BLEND_FOOT_ENABLED}" \
  +algo.config.runtime_residual_blend.foot_pos_onset="${RUNTIME_BLEND_FOOT_ONSET}" \
  +algo.config.runtime_residual_blend.foot_pos_threshold="${RUNTIME_BLEND_FOOT_THRESHOLD}" \
  "+algo.config.runtime_residual_blend.foot_pos_body_names=${RUNTIME_BLEND_FOOT_BODY_NAMES}" \
  +algo.config.runtime_residual_blend.foot_pos_side_specific="${RUNTIME_BLEND_FOOT_SIDE_SPECIFIC}" \
  "+algo.config.runtime_residual_blend.foot_pos_action_name_tokens=${RUNTIME_BLEND_FOOT_ACTION_TOKENS}" \
  +algo.config.runtime_residual_blend.min_residual_gate="${RUNTIME_BLEND_MIN_GATE}" \
  +algo.config.runtime_residual_blend.max_residual_gate="${RUNTIME_BLEND_MAX_GATE}" \
  +algo.config.runtime_residual_blend.exponent="${RUNTIME_BLEND_EXPONENT}" \
  "+algo.config.runtime_residual_blend.passthrough_action_name_tokens=${RUNTIME_BLEND_PASSTHROUGH_TOKENS}" \
  +algo.config.runtime_residual_blend.passthrough_residual_gate="${RUNTIME_BLEND_PASSTHROUGH_GATE}"

status=$?
echo "x2_sonic_lora_smoke_end=$(date -Is)"
echo "x2_sonic_lora_smoke_status=${status}"
exit "${status}"
} 2>&1 | tee "${CONSOLE_LOG}"
status=${PIPESTATUS[0]}
set -e
exit "${status}"
