#!/usr/bin/env bash
set -euo pipefail

# Deterministic contact-aware gait panel for the three Stage18 policy points.
# Usage: bash scripts/run_x2_stage19_foot_panel.sh CHECKPOINT_LABEL DOMAIN [STEPS]
#   CHECKPOINT_LABEL: warm200 | interp025 | step900
#   DOMAIN: ideal | filter | delay | noise | nominal(alias of delay)

ROOT=/home/humanplus/x2_teleop_final/x2_sonic
PROJECT_ROOT=/home/humanplus/projects/ZHY/CWI_CrossEmbodiment_Sim
LOG_ROOT="${PROJECT_ROOT}/logs"
LABEL="${1:?checkpoint label required: warm200|interp025|step900}"
DOMAIN="${2:?domain required: ideal|nominal}"
STEPS="${3:-400}"
SEED_VALUE="${SEED_VALUE:-0}"
CHECKPOINT_OVERRIDE="${CHECKPOINT_OVERRIDE:-}"
PANEL_TAG="${PANEL_TAG:-exact_v1}"
PANEL_NAME="${PANEL_NAME:-foot_core6}"
MOTION_FILE_VALUE="${MOTION_FILE_VALUE:-${ROOT}/motion_lib_x2/stage19_foot_core6}"
NUM_ENVS_VALUE="${NUM_ENVS_VALUE:-6}"
MOTIONS_VALUE="${MOTIONS_VALUE:-${NUM_ENVS_VALUE}}"
ENCODER_MODE="${ENCODER_MODE:-teleop}"
ACTION_SCALE_MULT_VALUE="${ACTION_SCALE_MULT_VALUE:-1.0}"
ACTION_SCALE_JOINT_MULTIPLIERS_VALUE="${ACTION_SCALE_JOINT_MULTIPLIERS_VALUE:-}"
X2_ACTION_SCALE_PROFILE_VALUE="${X2_ACTION_SCALE_PROFILE_VALUE:-foundation_hybrid}"
X2_COLLISION_PROFILE_VALUE="${X2_COLLISION_PROFILE_VALUE:-mesh}"
X2_PD_PROFILE_VALUE="${X2_PD_PROFILE_VALUE:-foundation_stiff_lower}"
SIM_DT_VALUE="${SIM_DT_VALUE:-0.005}"
DECIMATION_VALUE="${DECIMATION_VALUE:-4}"
PRESERVE_LORA_CHECKPOINT_VALUE="${PRESERVE_LORA_CHECKPOINT_VALUE:-false}"
SEMANTIC_COPY_STRICT_VALUE="${SEMANTIC_COPY_STRICT_VALUE:-false}"
SEMANTIC_NEUTRAL_INIT_UNMAPPED_VALUE="${SEMANTIC_NEUTRAL_INIT_UNMAPPED_VALUE:-false}"
ACTOR_LORA_PREFIXES_VALUE="${ACTOR_LORA_PREFIXES_VALUE:-[actor_module.decoders.g1_dyn]}"
ACTOR_INPUT_MASK_ENABLED_VALUE="${ACTOR_INPUT_MASK_ENABLED_VALUE:-false}"
ACTOR_INPUT_MASK_LAYERS_VALUE="${ACTOR_INPUT_MASK_LAYERS_VALUE:-[actor_module.decoders.g1_dyn.module.0]}"
ACTOR_INPUT_MASK_DECODER_VALUE="${ACTOR_INPUT_MASK_DECODER_VALUE:-g1_dyn}"
ACTOR_INPUT_MASK_FEATURES_VALUE="${ACTOR_INPUT_MASK_FEATURES_VALUE:-[command_multi_future_foot_contacts]}"
ACTOR_OUTPUT_MASK_ENABLED_VALUE="${ACTOR_OUTPUT_MASK_ENABLED_VALUE:-false}"
ACTOR_OUTPUT_MASK_LAYERS_VALUE="${ACTOR_OUTPUT_MASK_LAYERS_VALUE:-[actor_module.decoders.g1_dyn.module.12]}"
ACTOR_OUTPUT_MASK_TOKENS_VALUE="${ACTOR_OUTPUT_MASK_TOKENS_VALUE:-[shoulder_,elbow_,wrist_]}"
ACTOR_OUTPUT_AUX_TOKENS_VALUE="${ACTOR_OUTPUT_AUX_TOKENS_VALUE:-[]}"
ACTOR_OUTPUT_AUX_SCALE_VALUE="${ACTOR_OUTPUT_AUX_SCALE_VALUE:-0.0}"
ACTOR_OUTPUT_UNSELECTED_SCALE_VALUE="${ACTOR_OUTPUT_UNSELECTED_SCALE_VALUE:-0.0}"
ACTOR_DECODER_ACTION_PROJECTION_ENABLED_VALUE="${ACTOR_DECODER_ACTION_PROJECTION_ENABLED_VALUE:-false}"
ACTOR_DECODER_ACTION_PROJECTION_DECODER_VALUE="${ACTOR_DECODER_ACTION_PROJECTION_DECODER_VALUE:-g1_dyn}"
RESPONSE_AWARE_LORA_ENABLED_VALUE="${RESPONSE_AWARE_LORA_ENABLED_VALUE:-false}"
RESPONSE_AWARE_LORA_LAYERS_VALUE="${RESPONSE_AWARE_LORA_LAYERS_VALUE:-[actor_module.decoders.g1_dyn.module.12]}"
RESPONSE_AWARE_INPUT_SCALE_VALUE="${RESPONSE_AWARE_INPUT_SCALE_VALUE:-1.0}"
RESPONSE_AWARE_HIDDEN_DIM_VALUE="${RESPONSE_AWARE_HIDDEN_DIM_VALUE:-64}"
RESPONSE_AWARE_HISTORY_LENGTH_VALUE="${RESPONSE_AWARE_HISTORY_LENGTH_VALUE:-4}"
RESPONSE_AWARE_JOINT_COUNT_VALUE="${RESPONSE_AWARE_JOINT_COUNT_VALUE:-29}"
RESPONSE_AWARE_TARGET_POSITION_SCALE_VALUE="${RESPONSE_AWARE_TARGET_POSITION_SCALE_VALUE:-1.0}"
RESPONSE_AWARE_JOINT_POSITION_SCALE_VALUE="${RESPONSE_AWARE_JOINT_POSITION_SCALE_VALUE:-1.0}"
RESPONSE_AWARE_JOINT_VELOCITY_SCALE_VALUE="${RESPONSE_AWARE_JOINT_VELOCITY_SCALE_VALUE:-0.1}"
RESPONSE_AWARE_TRACKING_ERROR_SCALE_VALUE="${RESPONSE_AWARE_TRACKING_ERROR_SCALE_VALUE:-1.0}"
RESPONSE_AWARE_JOINT_INCLUDE_TOKENS_VALUE="${RESPONSE_AWARE_JOINT_INCLUDE_TOKENS_VALUE:-[]}"
RESPONSE_AWARE_OUTPUT_ACTION_TOKENS_VALUE="${RESPONSE_AWARE_OUTPUT_ACTION_TOKENS_VALUE:-[]}"
RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR_VALUE="${RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR_VALUE:-false}"
RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE_VALUE="${RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE_VALUE:-10.0}"
RESPONSE_AWARE_TRAIN_RESPONSE_ONLY_VALUE="${RESPONSE_AWARE_TRAIN_RESPONSE_ONLY_VALUE:-false}"
ANCHOR_POS_THRESHOLD_VALUE="${ANCHOR_POS_THRESHOLD_VALUE:-10}"
ANCHOR_ORI_FULL_THRESHOLD_VALUE="${ANCHOR_ORI_FULL_THRESHOLD_VALUE:-10}"
EE_BODY_POS_THRESHOLD_VALUE="${EE_BODY_POS_THRESHOLD_VALUE:-10}"
FOOT_POS_XYZ_THRESHOLD_VALUE="${FOOT_POS_XYZ_THRESHOLD_VALUE:-10}"
ACTOR_LEARNING_RATE_VALUE="${ACTOR_LEARNING_RATE_VALUE:-1e-12}"
CRITIC_LEARNING_RATE_VALUE="${CRITIC_LEARNING_RATE_VALUE:-0}"
if [[ -z "${ACTION_SCALE_JOINT_MULTIPLIERS_VALUE}" ]]; then
  ACTION_SCALE_JOINT_MULTIPLIERS_VALUE='{}'
fi

case "${ENCODER_MODE}" in
  teleop) ENCODER_SAMPLE_PROBS='{g1:0.0,teleop:1.0,smpl:0.0}' ;;
  g1) ENCODER_SAMPLE_PROBS='{g1:1.0,teleop:0.0,smpl:0.0}' ;;
  smpl) ENCODER_SAMPLE_PROBS='{g1:0.0,teleop:0.0,smpl:1.0}' ;;
  *) echo "unsupported encoder mode: ${ENCODER_MODE}" >&2; exit 2 ;;
esac

if [[ -n "${CHECKPOINT_OVERRIDE}" ]]; then
  CHECKPOINT="${CHECKPOINT_OVERRIDE}"
else
  case "${LABEL}" in
    warm200)
      CHECKPOINT="${ROOT}/checkpoints/x2_stage18_warm200_actor_faithful1000_critic_seed.pt"
      ;;
    interp025)
      CHECKPOINT="${ROOT}/checkpoints/x2_stage18_interp_seed_to_step900_alpha025.pt"
      ;;
    step900)
      CHECKPOINT="${ROOT}/logs/ppo_dryrun/x2_stage18_any2any_warm200_clean291_response_small1000_v1/model_step_000900.pt"
      ;;
    *)
      echo "unsupported checkpoint label without CHECKPOINT_OVERRIDE: ${LABEL}" >&2
      exit 2
      ;;
  esac
fi

EVAL_OBSERVATION_CORRUPTION_VALUE=false
case "${DOMAIN}" in
  ideal) ACTUATOR_RESPONSE_MODE=off ;;
  filter) ACTUATOR_RESPONSE_MODE=session0304_filter_only ;;
  delay|nominal) ACTUATOR_RESPONSE_MODE=session0304_nominal ;;
  noise)
    ACTUATOR_RESPONSE_MODE=session0304_nominal
    EVAL_OBSERVATION_CORRUPTION_VALUE=true
    ;;
  *)
    echo "unsupported domain: ${DOMAIN}" >&2
    exit 2
    ;;
esac

[[ -f "${CHECKPOINT}" ]] || { echo "missing checkpoint: ${CHECKPOINT}" >&2; exit 2; }

RUN_NAME="x2_stage19_${PANEL_NAME}_${LABEL}_${DOMAIN}_${ENCODER_MODE}_${PANEL_TAG}_s${STEPS}"
RUN_DIR="${LOG_ROOT}/${RUN_NAME}"
# Rollout traces are append-only.  Reusing an evaluation name silently mixes
# episodes from different physics/checkpoint settings and corrupts contact
# cycle counts.  Require an explicit new tag instead of overwriting evidence.
if [[ -e "${RUN_DIR}/x2_wrist_rollout_trace.jsonl" ]]; then
  echo "refusing to append to existing evaluation trace: ${RUN_DIR}" >&2
  echo "choose a fresh LABEL/PANEL_TAG" >&2
  exit 3
fi
env \
  RUN_NAME="${RUN_NAME}" \
  RUN_KIND=evaluation \
  CHECKPOINT="${CHECKPOINT}" \
  RESUME=false \
  EXP_CONFIG="${EXP_CONFIG_VALUE:-manager/universal_token/all_modes/sonic_x2_phuma_response_context}" \
  MOTION_FILE="${MOTION_FILE_VALUE}" \
  NUM_ENVS="${NUM_ENVS_VALUE}" \
  STEPS_PER_ENV="${STEPS}" \
  ITERS=1 \
  MOTIONS="${MOTIONS_VALUE}" \
  SEED="${SEED_VALUE}" \
  CLEAN_EVAL=true \
  CLEAN_COMMAND_INIT=true \
  TRAIN_WITH_EVALUATING_ENV=true \
  DETERMINISTIC_ROLLOUT=true \
  START_FROM_FIRST_FRAME=true \
  FREEZE_FRAME_AUG=false \
  ADAPTIVE_SAMPLING_ENABLED=false \
  SOURCE_CANONICAL_REFERENCE=true \
  ENCODER_SAMPLE_PROBS="${ENCODER_SAMPLE_PROBS}" \
  REWARD_POINT_MODE=source3 \
  TRACKED_BODY_SET=source14 \
  REWARD_WRIST_LINK=roll \
  EE_WRIST_LINK=roll \
  ANTI_SHAKE_BODY_NAMES='[left_wrist_roll_link,right_wrist_roll_link]' \
  FIX_BASE=false \
  UPPER_BODY_ONLY_ACTION=false \
  TERRAIN_TYPE=plane \
  X2_PD_PROFILE="${X2_PD_PROFILE_VALUE}" \
  X2_ACTION_SCALE_PROFILE="${X2_ACTION_SCALE_PROFILE_VALUE}" \
  X2_COLLISION_PROFILE="${X2_COLLISION_PROFILE_VALUE}" \
  SIM_DT="${SIM_DT_VALUE}" \
  DECIMATION="${DECIMATION_VALUE}" \
  ACTION_SCALE_MULT="${ACTION_SCALE_MULT_VALUE}" \
  ACTION_SCALE_JOINT_MULTIPLIERS="${ACTION_SCALE_JOINT_MULTIPLIERS_VALUE}" \
  ACTUATOR_RESPONSE_MODE="${ACTUATOR_RESPONSE_MODE}" \
  EVAL_OBSERVATION_CORRUPTION="${EVAL_OBSERVATION_CORRUPTION_VALUE}" \
  ACTION_PREEMPHASIS_ENABLED="${ACTION_PREEMPHASIS_ENABLED:-false}" \
  ACTION_PREEMPHASIS_STRENGTH="${ACTION_PREEMPHASIS_STRENGTH:-0.0}" \
  ACTION_PREEMPHASIS_MAX_DELTA_RAD="${ACTION_PREEMPHASIS_MAX_DELTA_RAD:-0.05}" \
  ACTION_PREEMPHASIS_GROUPS="${ACTION_PREEMPHASIS_GROUPS:-[legs,feet,waist]}" \
  ACTUATOR_GAIN_RANDOMIZATION=off \
  WRIST_DIAGNOSTICS=true \
  RENDER_RESULTS=false \
  ANCHOR_POS_THRESHOLD="${ANCHOR_POS_THRESHOLD_VALUE}" \
  ANCHOR_ORI_FULL_THRESHOLD="${ANCHOR_ORI_FULL_THRESHOLD_VALUE}" \
  EE_BODY_POS_THRESHOLD="${EE_BODY_POS_THRESHOLD_VALUE}" \
  FOOT_POS_XYZ_THRESHOLD="${FOOT_POS_XYZ_THRESHOLD_VALUE}" \
  ACTOR_LEARNING_RATE="${ACTOR_LEARNING_RATE_VALUE}" \
  CRITIC_LEARNING_RATE="${CRITIC_LEARNING_RATE_VALUE}" \
  PPO_EPOCHS=1 \
  NUM_MINI_BATCHES=1 \
  SAVE_FREQUENCY=9999 \
  SAVE_LAST_FREQUENCY=9999 \
  TRAIN_ACTOR_LORA=true \
  TRAIN_CRITIC_LORA=false \
  TRAIN_BOUNDARY_KEYS='[]' \
  PRESERVE_LORA_CHECKPOINT="${PRESERVE_LORA_CHECKPOINT_VALUE}" \
  ACTOR_LORA_PREFIXES="${ACTOR_LORA_PREFIXES_VALUE}" \
  ACTOR_INPUT_MASK_ENABLED="${ACTOR_INPUT_MASK_ENABLED_VALUE}" \
  ACTOR_INPUT_MASK_LAYERS="${ACTOR_INPUT_MASK_LAYERS_VALUE}" \
  ACTOR_INPUT_MASK_DECODER="${ACTOR_INPUT_MASK_DECODER_VALUE}" \
  ACTOR_INPUT_MASK_FEATURES="${ACTOR_INPUT_MASK_FEATURES_VALUE}" \
  SEMANTIC_COPY_STRICT="${SEMANTIC_COPY_STRICT_VALUE}" \
  SEMANTIC_NEUTRAL_INIT_UNMAPPED="${SEMANTIC_NEUTRAL_INIT_UNMAPPED_VALUE}" \
  ACTOR_OUTPUT_MASK_ENABLED="${ACTOR_OUTPUT_MASK_ENABLED_VALUE}" \
  ACTOR_OUTPUT_MASK_LAYERS="${ACTOR_OUTPUT_MASK_LAYERS_VALUE}" \
  ACTOR_OUTPUT_MASK_TOKENS="${ACTOR_OUTPUT_MASK_TOKENS_VALUE}" \
  ACTOR_OUTPUT_AUX_TOKENS="${ACTOR_OUTPUT_AUX_TOKENS_VALUE}" \
  ACTOR_OUTPUT_AUX_SCALE="${ACTOR_OUTPUT_AUX_SCALE_VALUE}" \
  ACTOR_OUTPUT_UNSELECTED_SCALE="${ACTOR_OUTPUT_UNSELECTED_SCALE_VALUE}" \
  ACTOR_DECODER_ACTION_PROJECTION_ENABLED="${ACTOR_DECODER_ACTION_PROJECTION_ENABLED_VALUE}" \
  ACTOR_DECODER_ACTION_PROJECTION_DECODER="${ACTOR_DECODER_ACTION_PROJECTION_DECODER_VALUE}" \
  RESPONSE_AWARE_LORA_ENABLED="${RESPONSE_AWARE_LORA_ENABLED_VALUE}" \
  RESPONSE_AWARE_LORA_LAYERS="${RESPONSE_AWARE_LORA_LAYERS_VALUE}" \
  RESPONSE_AWARE_INPUT_SCALE="${RESPONSE_AWARE_INPUT_SCALE_VALUE}" \
  RESPONSE_AWARE_HIDDEN_DIM="${RESPONSE_AWARE_HIDDEN_DIM_VALUE}" \
  RESPONSE_AWARE_HISTORY_LENGTH="${RESPONSE_AWARE_HISTORY_LENGTH_VALUE}" \
  RESPONSE_AWARE_JOINT_COUNT="${RESPONSE_AWARE_JOINT_COUNT_VALUE}" \
  RESPONSE_AWARE_TARGET_POSITION_SCALE="${RESPONSE_AWARE_TARGET_POSITION_SCALE_VALUE}" \
  RESPONSE_AWARE_JOINT_POSITION_SCALE="${RESPONSE_AWARE_JOINT_POSITION_SCALE_VALUE}" \
  RESPONSE_AWARE_JOINT_VELOCITY_SCALE="${RESPONSE_AWARE_JOINT_VELOCITY_SCALE_VALUE}" \
  RESPONSE_AWARE_TRACKING_ERROR_SCALE="${RESPONSE_AWARE_TRACKING_ERROR_SCALE_VALUE}" \
  RESPONSE_AWARE_JOINT_INCLUDE_TOKENS="${RESPONSE_AWARE_JOINT_INCLUDE_TOKENS_VALUE}" \
  RESPONSE_AWARE_OUTPUT_ACTION_TOKENS="${RESPONSE_AWARE_OUTPUT_ACTION_TOKENS_VALUE}" \
  RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR="${RESPONSE_AWARE_CONTACT_GATE_BY_TRACKING_ERROR_VALUE}" \
  RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE="${RESPONSE_AWARE_TRACKING_ERROR_ACTIVITY_SCALE_VALUE}" \
  RESPONSE_AWARE_TRAIN_RESPONSE_ONLY="${RESPONSE_AWARE_TRAIN_RESPONSE_ONLY_VALUE}" \
  CLAMP_NOISE_STD=false \
  bash "${PROJECT_ROOT}/scripts/run_dcpeft_stage152.sh"
