#!/usr/bin/env python3
"""Pure-offline Phase18 manifest and zero-update gate audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from official_x2.recovery_reset_curriculum import gait_phase_from_steps
from official_x2.recovery_suffix_aggregation import sha256_file
from official_x2.role_aware_recovery_curriculum import load_manifest, resolve_rows


ROLES = ("success", "critical", "height_fail")


def inverse_rotate_xyzw(quaternion: np.ndarray, vector: np.ndarray) -> np.ndarray:
    xyz = quaternion[:3]
    w = quaternion[3]
    cross = 2.0 * np.cross(xyz, vector)
    return vector - w * cross + np.cross(xyz, cross)


def source_reconstruction(rows: list[dict]) -> dict:
    group_max = {"body_linear_velocity": 0.0, "body_angular_velocity": 0.0, "projected_gravity": 0.0, "gait_phase": 0.0}
    for row in rows:
        physical = row["physical_state"]
        q = np.asarray(physical["root_quaternion_xyzw"], dtype=np.float64)
        obs = np.asarray(row["observation_93d"], dtype=np.float64)
        body_linear = inverse_rotate_xyzw(q, np.asarray(physical["root_linear_velocity_world_mps"], dtype=np.float64))
        body_angular = inverse_rotate_xyzw(q, np.asarray(physical["root_angular_velocity_world_radps"], dtype=np.float64))
        gravity = inverse_rotate_xyzw(q, np.asarray([0.0, 0.0, -1.0]))
        step = np.asarray([round(float(row["stop_elapsed_s"]) / 0.02)])
        moving = np.asarray([np.linalg.norm(row["gait_phase"][:2]) > 0.5])
        gait = gait_phase_from_steps(step, moving)[0]
        group_max["body_linear_velocity"] = max(group_max["body_linear_velocity"], float(np.max(np.abs(body_linear - obs[:3]))))
        group_max["body_angular_velocity"] = max(group_max["body_angular_velocity"], float(np.max(np.abs(body_angular - obs[3:6]))))
        group_max["projected_gravity"] = max(group_max["projected_gravity"], float(np.max(np.abs(gravity - obs[6:9]))))
        group_max["gait_phase"] = max(group_max["gait_phase"], float(np.max(np.abs(gait - obs[89:93]))))
    return group_max


def build_report(manifest_path: Path, result_dir: Path) -> dict:
    manifest = load_manifest(manifest_path)
    roles = {}
    for role in ROLES:
        result_path = result_dir / f"{role}.json"
        result = json.loads(result_path.read_text(encoding="utf-8"))
        rows = resolve_rows(manifest, result["fixed_manifest_indices"])
        errors = result.get("result", {}).get("snapshot_max_errors", {})
        physical_action_keys = [
            "joint_position_rad", "joint_velocity_radps", "root_position_m",
            "root_quaternion_one_minus_abs_dot", "root_linear_velocity_mps",
            "root_angular_velocity_radps", "policy_previous_action",
            "manager_action", "manager_previous_action", "term_effective_issued_action",
            "episode_clock_steps", "policy_command",
        ]
        roles[role] = {
            "result_path": str(result_path),
            "result_sha256": sha256_file(result_path),
            "passed": bool(result.get("passed")),
            "selected_env_count": result.get("result", {}).get("selected_env_count"),
            "physical_action_history_max_error": max(float(errors.get(key, float("inf"))) for key in physical_action_keys),
            "policy_observation_93d_max_error": errors.get("policy_observation_93d"),
            "controller_registry_hash_exact": result.get("result", {}).get("controller_registry_hash_exact"),
            "source_reference_exact": result.get("result", {}).get("source_reference_exact"),
            "source_reconstruction_max_error": source_reconstruction(rows),
            "failure_interpretation": (
                None if result.get("passed") else
                "Source 93D is not exactly generated by the injected physical/clock state for this fixed batch; do not override actor observations or train."
            ),
        }
    all_pass = all(item["passed"] for item in roles.values())
    return {
        "stage": "BASE Phase18 role-aware reset curriculum and zero-update injection gate",
        "hypothesis": "Phase17 can form a source-reference-only, outcome-stratified safe reset asset whose physical and actor-visible state inject exactly into StatefulRecoveryRLEnv.",
        "intervention": "Build an immutable role-aware manifest and inject fixed 16-env batches for success, critical, and pre-collapse height-fail at zero PPO/optimizer updates.",
        "control": "reset_fraction=0 returns before opening the manifest and consumes no reset RNG; all actual actions are restored as history/state only and are never imitation labels.",
        "manifest": {
            "path": str(manifest_path), "file_sha256": sha256_file(manifest_path),
            "content_sha256": manifest["content_sha256"], "counts": manifest["counts"],
            "source_reference_only": True, "actions_are_imitation_labels": False,
        },
        "zero_update_probe": {"roles": roles, "all_roles_pass": all_pass, "ppo_updates": 0, "optimizer_steps": 0},
        "gate": {
            "asset_schema_hash_eligibility_pass": True,
            "state_injection_all_roles_pass": all_pass,
            "training_unlocked": False,
            "decision": "STOP_LOCKED" if not all_pass else "READY_FOR_PREREG_REVIEW_ONLY",
        },
        "result": (
            "The role-aware asset is valid and all three roles have safe eligible rows, but the exact state-injection gate fails for success and height-fail because their recorded 93D actor input is not fully reconstructible from the saved physical/clock state."
        ),
        "conclusion": "Keep training locked. Directly forcing the saved 93D vector would create a reset/rollout observation mismatch and is not an acceptable repair.",
        "five_update_preregistration_draft": {
            "status": "BLOCKED_ON_ALL_ROLE_EXACT_INJECTION",
            "source_checkpoint": "freeze the same independent stand/recovery backend used by the paired control",
            "control": "role_aware_reset_fraction=0.00",
            "candidate": "role_aware_reset_fraction=0.05; outcome role sampled 1:1:1, then one eligible source row uniformly within role",
            "actions": "history/state only; no behavior cloning or imitation loss",
            "updates": 5,
            "seed": 47,
            "paired_requirements": "same checkpoint, optimizer, minibatches, RNG contract and official 5-episode matched gate",
            "promotion": "candidate no worse than source/control and stiff-fixed full success moves toward 5/5",
            "abort": "any actor/interface mismatch, any official regression, or any non-exact reset field",
            "not_authorized_to_run": True,
        },
        "next": "Repair or recapture the source contract so root/IMU angular velocity, projected gravity and gait/contact observation are deterministically tied to the stored physical/controller state; then rerun only the exact injection gate before reconsidering the draft.",
        "boundaries": [
            "IsaacLab injection against official AimDK MuJoCo snapshots; not real hardware.",
            "Controller snapshot is hash-exact in an env registry, but future official brake/latch consumption is not proven.",
            "The wrapper originally continued because Isaac Kit returned a clean process status after recording a failed JSON gate; it is now fail-closed on the JSON passed field. No training occurred."
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, default=Path("manifests/x2_phase17_role_aware_reset_curriculum.json"))
    parser.add_argument("--result-dir", type=Path, default=Path("results/phase18_role_aware_zero_update"))
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    report = build_report(args.manifest, args.result_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(args.output), "decision": report["gate"]["decision"], "training_unlocked": False}, indent=2))


if __name__ == "__main__":
    main()
