/**
 * @file policy_parameters.hpp
 * @brief Motor constants, PID gains, joint mappings, action scales, and default
 *        standing angles for the AgiBot X2 Ultra 31-DOF policy.
 *
 * AUTOGENERATED — DO NOT EDIT BY HAND.
 *
 * Regenerate via:
 *   python gear_sonic_deploy/scripts/codegen_x2_policy_parameters.py
 *
 * Source of truth: gear_sonic/scripts/eval_x2_mujoco.py
 *   - MUJOCO_JOINT_NAMES, IL_TO_MJ_DOF, MJ_TO_IL_DOF
 *   - ARMATURES (per joint family) + NATURAL_FREQ + DAMPING_RATIO
 *   - EFFORT_LIMITS (per joint family)
 *   - DEFAULT_JOINT_POS (training reset pose, MuJoCo joint order)
 *
 * ## Joint Ordering
 *
 * Two ordering conventions coexist:
 *   - **MuJoCo order** — used by the simulator, motion-lib PKLs, and the
 *     X2 robot's URDF kinematic tree.
 *   - **IsaacLab order** — used internally by the trained policy and the
 *     proprioception buffer. The IL ordering interleaves left/right
 *     joints (hip_pitch L/R/.../waist_yaw/...).
 *
 * ``isaaclab_to_mujoco`` and ``mujoco_to_isaaclab`` provide the remapping.
 *
 * ## PID Gain Computation
 *
 * Per-joint stiffness and damping derive from a per-armature
 * critically-damped second-order model:
 *   stiffness = armature * (2 * pi * 10 Hz)^2
 *   damping   = 2 * zeta * armature * (2 * pi * 10 Hz)        (zeta = 2.0)
 *
 * The X2 (unlike the G1) uses joint-keyword-based armature lookup rather
 * than a small fixed motor-type taxonomy, so the per-joint gains are
 * baked in directly below.
 *
 * ## Action Scaling
 *
 * Policy actions are scaled per joint:
 *   action_scale = 0.25 * effort_limit / stiffness
 *
 * Final command: target = action * action_scale + default_angle.
 */

#ifndef POLICY_PARAMETERS_HPP
#define POLICY_PARAMETERS_HPP

#include <array>
#include <cstddef>

// ---------- Robot dimensions ----------
constexpr std::size_t NUM_DOFS = 31;
constexpr std::size_t HISTORY_LEN = 10;
constexpr std::size_t NUM_FUTURE_FRAMES = 10;
constexpr double CONTROL_DT = 0.02;
constexpr double SIM_DT = 0.005;
constexpr int DECIMATION = 4;
constexpr double DT_FUTURE_REF = 0.1;

// ---------- Joint name table (MJCF order; canonical) ----------
const std::array<const char*, 31> mujoco_joint_names = {
    "left_hip_pitch_joint",
    "left_hip_roll_joint",
    "left_hip_yaw_joint",
    "left_knee_joint",
    "left_ankle_pitch_joint",
    "left_ankle_roll_joint",
    "right_hip_pitch_joint",
    "right_hip_roll_joint",
    "right_hip_yaw_joint",
    "right_knee_joint",
    "right_ankle_pitch_joint",
    "right_ankle_roll_joint",
    "waist_yaw_joint",
    "waist_pitch_joint",
    "waist_roll_joint",
    "left_shoulder_pitch_joint",
    "left_shoulder_roll_joint",
    "left_shoulder_yaw_joint",
    "left_elbow_joint",
    "left_wrist_yaw_joint",
    "left_wrist_pitch_joint",
    "left_wrist_roll_joint",
    "right_shoulder_pitch_joint",
    "right_shoulder_roll_joint",
    "right_shoulder_yaw_joint",
    "right_elbow_joint",
    "right_wrist_yaw_joint",
    "right_wrist_pitch_joint",
    "right_wrist_roll_joint",
    "head_yaw_joint",
    "head_pitch_joint",
};

// ---------- Joint ordering remaps ----------
// IL_TO_MJ_DOF[il_idx] = mj_idx  -> use to send IL-ordered tensors to MJ/SDK
const std::array<int, 31> isaaclab_to_mujoco = {0, 6, 12, 1, 7, 13, 2, 8, 14, 3, 9, 29, 15, 22, 4, 10, 30, 16, 23, 5, 11, 17, 24, 18, 25, 19, 26, 20, 27, 21, 28};
// MJ_TO_IL_DOF[mj_idx] = il_idx  -> use to map robot/MJ readings into IL order
const std::array<int, 31> mujoco_to_isaaclab = {0, 3, 6, 9, 14, 19, 1, 4, 7, 10, 15, 20, 2, 5, 8, 12, 17, 21, 23, 25, 27, 29, 13, 18, 22, 24, 26, 28, 30, 11, 16};

// ---------- PD gains (MuJoCo joint order) ----------
// kp[i] = ARMATURES[joint_family(i)] * (2*pi*10 Hz)^2  (Python: KP)
const std::array<double, 31> kps = {
    99.09842778, // left_hip_pitch_joint
    99.09842778, // left_hip_roll_joint
    99.09842778, // left_hip_yaw_joint
    99.09842778, // left_knee_joint
    21.37593465, // left_ankle_pitch_joint
    21.37593465, // left_ankle_roll_joint
    99.09842778, // right_hip_pitch_joint
    99.09842778, // right_hip_roll_joint
    99.09842778, // right_hip_yaw_joint
    99.09842778, // right_knee_joint
    21.37593465, // right_ankle_pitch_joint
    21.37593465, // right_ankle_roll_joint
    40.17923847, // waist_yaw_joint
    14.2506231, // waist_pitch_joint
    14.2506231, // waist_roll_joint
    14.2506231, // left_shoulder_pitch_joint
    14.2506231, // left_shoulder_roll_joint
    14.2506231, // left_shoulder_yaw_joint
    14.2506231, // left_elbow_joint
    14.2506231, // left_wrist_yaw_joint
    16.77832748, // left_wrist_pitch_joint
    16.77832748, // left_wrist_roll_joint
    14.2506231, // right_shoulder_pitch_joint
    14.2506231, // right_shoulder_roll_joint
    14.2506231, // right_shoulder_yaw_joint
    14.2506231, // right_elbow_joint
    14.2506231, // right_wrist_yaw_joint
    16.77832748, // right_wrist_pitch_joint
    16.77832748, // right_wrist_roll_joint
    16.77832748, // head_yaw_joint
    16.77832748, // head_pitch_joint
};

// kd[i] = 2 * 2.0 * ARMATURES[joint_family(i)] * (2*pi*10 Hz)  (Python: KD)
const std::array<double, 31> kds = {
    6.308801854, // left_hip_pitch_joint
    6.308801854, // left_hip_roll_joint
    6.308801854, // left_hip_yaw_joint
    6.308801854, // left_knee_joint
    0.9072228433, // left_ankle_pitch_joint
    0.9072228433, // left_ankle_roll_joint
    6.308801854, // right_hip_pitch_joint
    6.308801854, // right_hip_roll_joint
    6.308801854, // right_hip_yaw_joint
    6.308801854, // right_knee_joint
    0.9072228433, // right_ankle_pitch_joint
    0.9072228433, // right_ankle_roll_joint
    2.557889765, // waist_yaw_joint
    0.9072228433, // waist_pitch_joint
    0.9072228433, // waist_roll_joint
    0.9072228433, // left_shoulder_pitch_joint
    0.9072228433, // left_shoulder_roll_joint
    0.9072228433, // left_shoulder_yaw_joint
    0.9072228433, // left_elbow_joint
    0.9072228433, // left_wrist_yaw_joint
    1.068141502, // left_wrist_pitch_joint
    1.068141502, // left_wrist_roll_joint
    0.9072228433, // right_shoulder_pitch_joint
    0.9072228433, // right_shoulder_roll_joint
    0.9072228433, // right_shoulder_yaw_joint
    0.9072228433, // right_elbow_joint
    0.9072228433, // right_wrist_yaw_joint
    1.068141502, // right_wrist_pitch_joint
    1.068141502, // right_wrist_roll_joint
    1.068141502, // head_yaw_joint
    1.068141502, // head_pitch_joint
};

// ---------- Action scaling (MuJoCo joint order) ----------
// action_scale[i] = 0.25 * EFFORT_LIMITS[joint_family(i)] / kp[i]  (Python: ACTION_SCALE)
//
// AUTHORITY: models/x2_sonic_frozen_g1core_lora_v2.onnx.phi.json -> action_scales.x2
// (note that sidecar lists values in G1 IL order, not the MJ order used here).
// The sidecar is the codec calibration record shipped WITH the checkpoint, so it
// records what the policy was actually trained against. Do NOT regenerate this
// table from a live x2_ultra.py -- that file has moved since the checkpoint.
//
// 2026-08-29: corrected 6 entries that had been generated from the PRE
// 2026-07-14 motor-datasheet effort limits (waist pitch/roll 48 instead of 36,
// wrist pitch/roll 4.8 instead of 6.0). The other 25 were already bit-identical
// to the sidecar. Symptom of the stale waist value, per eval_x2_mujoco.py:88-93:
// "a stale waist 48 vs trained 36 over-pitched the torso 1.33x -> constant
// forward-fall/recovery-stepping on standing clips".
const std::array<double, 31> x2_action_scale = {
    0.3027293235, // left_hip_pitch_joint
    0.3027293235, // left_hip_roll_joint
    0.3027293235, // left_hip_yaw_joint
    0.3027293235, // left_knee_joint
    0.631551332, // left_ankle_pitch_joint
    0.4210342213, // left_ankle_roll_joint
    0.3027293235, // right_hip_pitch_joint
    0.3027293235, // right_hip_roll_joint
    0.3027293235, // right_hip_yaw_joint
    0.3027293235, // right_knee_joint
    0.631551332, // right_ankle_pitch_joint
    0.4210342213, // right_ankle_roll_joint
    0.7466542707, // waist_yaw_joint
    0.631551332, // waist_pitch_joint   (2026-08-29: was 0.8420684427, effort 48)
    0.631551332, // waist_roll_joint    (2026-08-29: was 0.8420684427, effort 48)
    0.631551332, // left_shoulder_pitch_joint
    0.631551332, // left_shoulder_roll_joint
    0.4210342213, // left_shoulder_yaw_joint
    0.4210342213, // left_elbow_joint
    0.4210342213, // left_wrist_yaw_joint
    0.08940104439, // left_wrist_pitch_joint (2026-08-29: was 0.07152083551, eff 4.8)
    0.08940104439, // left_wrist_roll_joint  (2026-08-29: was 0.07152083551, eff 4.8)
    0.631551332, // right_shoulder_pitch_joint
    0.631551332, // right_shoulder_roll_joint
    0.4210342213, // right_shoulder_yaw_joint
    0.4210342213, // right_elbow_joint
    0.4210342213, // right_wrist_yaw_joint
    0.08940104439, // right_wrist_pitch_joint (2026-08-29: was 0.07152083551, eff 4.8)
    0.08940104439, // right_wrist_roll_joint  (2026-08-29: was 0.07152083551, eff 4.8)
    0.03874045257, // head_yaw_joint
    0.008940104439, // head_pitch_joint
};

// ---------- Default standing pose (MuJoCo joint order, radians) ----------
// Matches gear_sonic/envs/.../x2_ultra.py InitialStateCfg (training reset pose).
const std::array<double, 31> default_angles = {
    -0.312, // left_hip_pitch_joint
    0, // left_hip_roll_joint
    0, // left_hip_yaw_joint
    0.669, // left_knee_joint
    -0.363, // left_ankle_pitch_joint
    0, // left_ankle_roll_joint
    -0.312, // right_hip_pitch_joint
    0, // right_hip_roll_joint
    0, // right_hip_yaw_joint
    0.669, // right_knee_joint
    -0.363, // right_ankle_pitch_joint
    0, // right_ankle_roll_joint
    0, // waist_yaw_joint
    0, // waist_pitch_joint
    0, // waist_roll_joint
    0.2, // left_shoulder_pitch_joint
    0.2, // left_shoulder_roll_joint
    0, // left_shoulder_yaw_joint
    -0.6, // left_elbow_joint
    0, // left_wrist_yaw_joint
    0, // left_wrist_pitch_joint
    0, // left_wrist_roll_joint
    0.2, // right_shoulder_pitch_joint
    -0.2, // right_shoulder_roll_joint
    0, // right_shoulder_yaw_joint
    -0.6, // right_elbow_joint
    0, // right_wrist_yaw_joint
    0, // right_wrist_pitch_joint
    0, // right_wrist_roll_joint
    0, // head_yaw_joint
    0, // head_pitch_joint
};

#endif // POLICY_PARAMETERS_HPP
