#ifndef AGI_X2_STAND_POSE_LOADER_HPP
#define AGI_X2_STAND_POSE_LOADER_HPP

/**
 * @file stand_pose_loader.hpp
 * @brief Loads the captured MC STAND_DEFAULT pose from a YAML config file.
 *
 * The YAML file is generated by the operator-side capture script
 * (see scripts/x2_capture_stand_pose.sh, or the inline capture done in the
 * conversation history that produced configs/x2_stand_default_pose.yaml).
 * It carries one row per joint, in the format:
 *
 *   group_name:
 *     - {name: <joint>, position: <rad>, velocity: <rad/s>,
 *        effort: <Nm>, stiffness: <kp>, damping: <kd>}
 *
 * We parse it with a small line regex rather than pulling in yaml-cpp,
 * because the format is fixed and machine-generated -- the regex is the
 * cheaper, fewer-deps option.
 *
 * The loader returns three 31-element arrays in MuJoCo joint order
 * (matches policy_parameters.hpp::default_angles): position targets, kp,
 * kd. velocity / effort columns are parsed but discarded -- HOLD_FOR_MC
 * holds a static pose, so they don't matter.
 */

#include "policy_parameters.hpp"

#include <array>
#include <cstddef>
#include <fstream>
#include <regex>
#include <stdexcept>
#include <string>
#include <unordered_map>

namespace agi_x2 {

struct StandPose {
  std::array<double, NUM_DOFS> position{};
  std::array<double, NUM_DOFS> stiffness{};  // MC-side kp from STAND_DEFAULT
  std::array<double, NUM_DOFS> damping{};    // MC-side kd from STAND_DEFAULT
  std::size_t parsed_count = 0;
};

/**
 * @brief Parse a stand-pose YAML file.
 * @throws std::runtime_error if the file is missing, unparseable, or any
 *         joint name is not in mujoco_joint_names.
 */
inline StandPose LoadStandPose(const std::string &path) {
  std::ifstream fh(path);
  if (!fh) {
    throw std::runtime_error("stand-pose YAML not found: " + path);
  }

  // Build a name -> mujoco-index map from the canonical joint-name table.
  std::unordered_map<std::string, std::size_t> name_to_idx;
  for (std::size_t i = 0; i < NUM_DOFS; ++i) {
    name_to_idx.emplace(mujoco_joint_names[i], i);
  }

  // One line per joint; the capture script writes them as
  //   - {name: NAME, position: P, velocity: V, effort: E, stiffness: K, damping: D}
  // We allow signed values with optional + / - and arbitrary whitespace.
  static const std::regex line_re(
      R"(name:\s*([A-Za-z0-9_]+)\s*,)"
      R"(\s*position:\s*([+-]?[0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?)\s*,)"
      R"(\s*velocity:\s*[+-]?[0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?\s*,)"
      R"(\s*effort:\s*[+-]?[0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?\s*,)"
      R"(\s*stiffness:\s*([+-]?[0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?)\s*,)"
      R"(\s*damping:\s*([+-]?[0-9]*\.?[0-9]+(?:[eE][+-]?[0-9]+)?))",
      std::regex::ECMAScript);

  StandPose out;
  std::string line;
  std::size_t lineno = 0;
  while (std::getline(fh, line)) {
    ++lineno;
    if (line.empty() || line.find('#') == 0) continue;
    std::smatch m;
    if (!std::regex_search(line, m, line_re)) continue;
    const std::string joint = m[1].str();
    auto it = name_to_idx.find(joint);
    if (it == name_to_idx.end()) {
      throw std::runtime_error(
          "stand-pose YAML at line " + std::to_string(lineno) +
          ": unknown joint name '" + joint +
          "' (not in mujoco_joint_names)");
    }
    const std::size_t idx = it->second;
    out.position[idx]  = std::stod(m[2].str());
    out.stiffness[idx] = std::stod(m[3].str());
    out.damping[idx]   = std::stod(m[4].str());
    ++out.parsed_count;
  }

  if (out.parsed_count != NUM_DOFS) {
    throw std::runtime_error(
        "stand-pose YAML " + path + ": expected " +
        std::to_string(NUM_DOFS) + " joints, found " +
        std::to_string(out.parsed_count));
  }
  return out;
}

}  // namespace agi_x2

#endif  // AGI_X2_STAND_POSE_LOADER_HPP
